"use client";
/* eslint-disable react-hooks/set-state-in-effect */
import { FormEvent,useCallback,useEffect,useState } from "react";
type Post={id:string;body:string;author:string|null;createdAt:string;likes:number;comments:number};
type Comment={id:string;body:string;authorId:string;author:string|null;createdAt:string};

export function CommunityFeed(){
 const [posts,setPosts]=useState<Post[]>([]),[body,setBody]=useState(""),[message,setMessage]=useState(""),[busy,setBusy]=useState(false),[openPost,setOpenPost]=useState<string|null>(null),[comments,setComments]=useState<Record<string,Comment[]>>({}),[commentDraft,setCommentDraft]=useState<Record<string,string>>({});
 const load=useCallback(async()=>{const r=await fetch("/api/community");if(r.ok)setPosts((await r.json()).posts)},[]);
 useEffect(()=>{void load()},[load]);
 function requireLogin(r:Response){if(r.status===401){window.location.assign("/login?returnTo=/community");return true}return false}
 async function submit(e:FormEvent){e.preventDefault();setBusy(true);setMessage("");const r=await fetch("/api/community",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({body})}),data=await r.json();if(requireLogin(r))return;setMessage(r.ok?"تم نشر مشاركتك":data.error);if(r.ok){setBody("");await load()}setBusy(false)}
 async function like(postId:string){const r=await fetch("/api/community/likes",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({postId})});if(requireLogin(r))return;const data=await r.json();if(r.ok)setPosts(x=>x.map(p=>p.id===postId?{...p,likes:Number(data.count)}:p));else setMessage(data.error||"تعذر تسجيل الإعجاب")}
 async function toggleComments(postId:string){if(openPost===postId){setOpenPost(null);return}setOpenPost(postId);if(comments[postId])return;const r=await fetch(`/api/community/comments?postId=${encodeURIComponent(postId)}`),data=await r.json();if(r.ok)setComments(x=>({...x,[postId]:data.comments}));else setMessage(data.error||"تعذر تحميل التعليقات")}
 async function addComment(e:FormEvent<HTMLFormElement>,postId:string){e.preventDefault();const text=(commentDraft[postId]??"").trim();if(!text)return;const r=await fetch("/api/community/comments",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({postId,body:text})});if(requireLogin(r))return;const data=await r.json();if(r.ok){setComments(x=>({...x,[postId]:[...(x[postId]??[]),data.comment]}));setCommentDraft(x=>({...x,[postId]:""}));setPosts(x=>x.map(p=>p.id===postId?{...p,comments:p.comments+1}:p))}else setMessage(data.error||"تعذر إضافة التعليق")}
 async function report(entityType:"community_post"|"community_comment",entityId:string){const reason=window.prompt("اكتب سبب البلاغ")?.trim();if(!reason)return;const r=await fetch("/api/community/reports",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({entityType,entityId,reason})});if(requireLogin(r))return;const data=await r.json();setMessage(r.ok?(data.duplicate?"البلاغ مسجل بالفعل وسيتم مراجعته.":"تم إرسال البلاغ للإدارة."):data.error||"تعذر إرسال البلاغ")}
 return <><div className="social-compose"><h2>اكتب لأهل ديرب</h2><form onSubmit={submit}><textarea required minLength={3} maxLength={2000} value={body} onChange={e=>setBody(e.target.value)} placeholder="إيه اللي حابب تشاركه؟"/><button className="primary" disabled={busy}>{busy?"جارٍ النشر...":"نشر"}</button></form>{message&&<p className="form-message ok">{message}</p>}</div><div className="social-feed">{posts.length===0?<div className="empty"><span>💬</span><h3>كن أول من يشارك</h3><p>لا توجد منشورات منشورة حتى الآن.</p></div>:posts.map(p=><article key={p.id}><div className="social-author"><span>👤</span><div><b>{p.author||"عضو من ديرب"}</b><small>{new Date(p.createdAt).toLocaleString("ar-EG")}</small></div></div><p>{p.body}</p><footer><button type="button" onClick={()=>like(p.id)}>♡ {p.likes} إعجاب</button><button type="button" onClick={()=>toggleComments(p.id)}>💬 {p.comments} تعليق</button><button type="button" onClick={()=>report("community_post",p.id)}>⚑ بلاغ</button></footer>{openPost===p.id&&<section className="community-comments"><div>{(comments[p.id]??[]).length===0?<p>لا توجد تعليقات بعد.</p>:(comments[p.id]??[]).map(c=><article key={c.id}><b>{c.author||"عضو من ديرب"}</b><p>{c.body}</p><small>{new Date(c.createdAt).toLocaleString("ar-EG")}</small><button type="button" onClick={()=>report("community_comment",c.id)}>بلاغ</button></article>)}</div><form onSubmit={e=>addComment(e,p.id)}><input value={commentDraft[p.id]??""} onChange={e=>setCommentDraft(x=>({...x,[p.id]:e.target.value}))} maxLength={1000} placeholder="اكتب تعليقًا..." aria-label="التعليق"/><button disabled={!(commentDraft[p.id]??"").trim()}>إرسال</button></form></section>}</article>)}</div></>;
}
