import Link from "next/link";
import { and,asc,eq } from "drizzle-orm";
import { notFound } from "next/navigation";
import { getDb } from "../../../db";
import { addresses,orderItems,orders,orderStatusHistory,stores } from "../../../db/pg-schema";
import { requireChatGPTUser } from "../../chatgpt-auth";
import { requireApiUser } from "../../lib/authz";
export const dynamic="force-dynamic";
const labels:Record<string,string>={pending:"جديد",confirmed:"تم التأكيد",preparing:"جارٍ التجهيز",ready:"جاهز",out_for_delivery:"خرج للتوصيل",delivered:"تم التسليم",cancelled:"ملغي",rejected:"مرفوض",refunded:"مسترد"};
export default async function OrderDetail({params}:{params:Promise<{id:string}>}){const {id}=await params;await requireChatGPTUser(`/orders/${id}`);const user=await requireApiUser(),db=getDb();const [order]=await db.select({id:orders.id,orderNumber:orders.orderNumber,status:orders.status,subtotal:orders.subtotal,discount:orders.discount,deliveryFee:orders.deliveryFee,total:orders.total,notes:orders.notes,createdAt:orders.createdAt,storeName:stores.name,storeSlug:stores.slug,addressLabel:addresses.label,street:addresses.street,building:addresses.building,floor:addresses.floor,landmark:addresses.landmark}).from(orders).innerJoin(stores,eq(stores.id,orders.storeId)).leftJoin(addresses,eq(addresses.id,orders.addressId)).where(and(eq(orders.id,id),eq(orders.customerId,user.id))).limit(1);if(!order)notFound();const [items,history]=await Promise.all([db.select().from(orderItems).where(eq(orderItems.orderId,id)),db.select().from(orderStatusHistory).where(eq(orderStatusHistory.orderId,id)).orderBy(asc(orderStatusHistory.createdAt))]);return <main className="market-page"><header><Link className="brand" href="/"><span className="brand-mark">د</span><strong>تفاصيل الطلب</strong></Link><Link className="ghost" href="/orders">كل طلباتي</Link></header><section className="order-detail"><div className="section-heading"><div><span className="kicker">{order.storeName}</span><h1>{order.orderNumber}</h1><p>{new Date(order.createdAt).toLocaleString("ar-EG")}</p></div><span className="status-pill">{labels[order.status]||order.status}</span></div><div className="content-split"><section className="form-card"><h2>الأصناف</h2><div className="data-table">{items.map(i=><article key={i.id}><div><b>{i.nameSnapshot}</b><small>{i.quantity} × {i.unitPrice.toLocaleString("ar-EG")} ج</small></div><strong>{i.lineTotal.toLocaleString("ar-EG")} ج</strong></article>)}</div><div className="order-totals"><p>الإجمالي قبل الخصم <b>{order.subtotal.toLocaleString("ar-EG")} ج</b></p><p>الخصم <b>{order.discount.toLocaleString("ar-EG")} ج</b></p><p>التوصيل <b>{order.deliveryFee.toLocaleString("ar-EG")} ج</b></p><p>الإجمالي النهائي <strong>{order.total.toLocaleString("ar-EG")} ج</strong></p></div></section><section className="form-card"><h2>التوصيل والمتابعة</h2>{order.addressLabel&&<div><b>{order.addressLabel}</b><p>{order.street}{order.building?` · مبنى ${order.building}`:""}{order.floor?` · دور ${order.floor}`:""}</p>{order.landmark&&<small>علامة مميزة: {order.landmark}</small>}</div>}<h3>خط سير الطلب</h3><div className="order-timeline">{history.map(h=><article key={h.id}><b>{labels[h.toStatus]||h.toStatus}</b><small>{new Date(h.createdAt).toLocaleString("ar-EG")}{h.note?` · ${h.note}`:""}</small></article>)}</div>{order.notes&&<p>ملاحظات: {order.notes}</p>}<Link className="text-button" href={`/store/${order.storeSlug}`}>فتح المتجر ←</Link></section></div></section></main>}
