"use client";
import { useState } from "react";
type Service={id:string;name:string;profession:string;phone:string;status:string};type Report={id:string;entityType:string;entityId:string;reason:string;status:string};type Question={id:string;title:string;status:string};type Ad={id:string;title:string;placement:string;status:string};type Driver={id:string;phone:string;vehicleType:string;status:string};
export function ModerationCenter({services,reports,questions,ads,drivers}:{services:Service[];reports:Report[];questions:Question[];ads:Ad[];drivers:Driver[]}){
 const [busy,setBusy]=useState(""),[message,setMessage]=useState("");
 async function act(entityType:"service"|"question"|"report"|"ad"|"driver",entityId:string,action:string){setBusy(entityId+action);setMessage("");const r=await fetch("/api/admin/moderation",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({entityType,entityId,action})}),data=await r.json();setMessage(r.ok?"تم تنفيذ الإجراء. حدّث الصفحة لرؤية الحالة الجديدة.":data.error||"تعذر تنفيذ الإجراء");setBusy("")}
 return <section className="admin-ops">{message&&<p className="form-message ok">{message}</p>}
  <article className="review-card"><div className="review-head"><div><span className="kicker">الخدمات</span><h2>مقدمو خدمات ينتظرون الاعتماد</h2></div><b>{services.length}</b></div><div className="review-list">{services.length===0?<p>لا توجد طلبات معلقة.</p>:services.map(x=><article key={x.id}><div><b>{x.name}</b><small>{x.profession} · {x.phone}</small></div><div><button className="approve" disabled={!!busy} onClick={()=>act("service",x.id,"approve")}>اعتماد</button><button className="reject" disabled={!!busy} onClick={()=>act("service",x.id,"reject")}>رفض</button></div></article>)}</div></article>
  <article className="review-card"><div className="review-head"><div><span className="kicker">البلاغات</span><h2>بلاغات المحتوى المفتوحة</h2></div><b>{reports.length}</b></div><div className="review-list">{reports.length===0?<p>لا توجد بلاغات مفتوحة.</p>:reports.map(x=><article key={x.id}><div><b>{x.reason}</b><small>{x.entityType} · {x.entityId}</small></div><div><button className="approve" disabled={!!busy} onClick={()=>act("report",x.id,"resolve")}>تم الحل</button><button className="reject" disabled={!!busy} onClick={()=>act("report",x.id,"dismiss")}>رفض البلاغ</button></div></article>)}</div></article>
  <article className="review-card"><div className="review-head"><div><span className="kicker">اسأل أهل ديرب</span><h2>أحدث الأسئلة المنشورة</h2></div><b>{questions.length}</b></div><div className="review-list">{questions.map(x=><article key={x.id}><div><b>{x.title}</b><small>{x.status}</small></div><div><button className="reject" disabled={!!busy} onClick={()=>act("question",x.id,"hide")}>إخفاء</button></div></article>)}</div></article>
  <article className="review-card"><div className="review-head"><div><span className="kicker">الإعلانات المدفوعة</span><h2>حملات تنتظر المراجعة</h2></div><b>{ads.length}</b></div><div className="review-list">{ads.length===0?<p>لا توجد حملات معلقة.</p>:ads.map(x=><article key={x.id}><div><b>{x.title}</b><small>{x.placement}</small></div><div><button className="approve" disabled={!!busy} onClick={()=>act("ad",x.id,"approve")}>اعتماد</button><button className="reject" disabled={!!busy} onClick={()=>act("ad",x.id,"reject")}>رفض</button></div></article>)}</div></article>
  <article className="review-card"><div className="review-head"><div><span className="kicker">التوصيل</span><h2>مندوبون ينتظرون الاعتماد</h2></div><b>{drivers.length}</b></div><div className="review-list">{drivers.length===0?<p>لا توجد طلبات معلقة.</p>:drivers.map(x=><article key={x.id}><div><b>{x.phone}</b><small>{x.vehicleType}</small></div><div><button className="approve" disabled={!!busy} onClick={()=>act("driver",x.id,"approve")}>اعتماد</button><button className="reject" disabled={!!busy} onClick={()=>act("driver",x.id,"reject")}>رفض</button></div></article>)}</div></article>
 </section>;
}
