import assert from "node:assert/strict";
import { readFile,readdir } from "node:fs/promises";
import { join } from "node:path";
import test from "node:test";
async function files(dir){const out=[];for(const entry of await readdir(dir,{withFileTypes:true})){const path=join(dir,entry.name);if(entry.isDirectory())out.push(...await files(path));else if(/\.(ts|tsx|js|mjs|json)$/.test(entry.name))out.push(path)}return out}
test("runtime contains no Supabase dependency and client modules contain no database credential",async()=>{const paths=[...await files("app"),...await files("db")],packageJson=JSON.parse(await readFile("package.json","utf8"));assert.equal(Object.keys({...packageJson.dependencies,...packageJson.devDependencies}).some(name=>/supabase/i.test(name)),false);for(const path of paths){const source=await readFile(path,"utf8");assert.doesNotMatch(source,/from\s+["'][^"']*supabase|require\(["'][^"']*supabase/i,path);const firstStatement=source.trimStart().split(/\r?\n/,1)[0];if(/^['\"]use client['\"];?$/.test(firstStatement))assert.doesNotMatch(source,/DATABASE_URL|S3_SECRET_ACCESS_KEY|SESSION_SECRET/,path)}});
test("private APIs derive identity on the server",async()=>{for(const path of ["app/api/orders/route.ts","app/api/messages/route.ts","app/api/notifications/route.ts","app/api/admin/stores/route.ts"]){const source=await readFile(path,"utf8");assert.match(source,/requireApiUser|requireRole/,path)}});
test("passwords use PBKDF2 and sessions use HttpOnly cookies",async()=>{assert.match(await readFile("app/lib/passwords.ts","utf8"),/PBKDF2/);assert.match(await readFile("app/lib/session-cookie.ts","utf8"),/HttpOnly/)});
test("ownership-sensitive modules check server identity",async()=>{for(const path of ["app/api/account/route.ts","app/api/cart/route.ts","app/api/support/route.ts","app/api/delivery/route.ts","app/api/subscriptions/route.ts","app/api/products/route.ts","app/api/stores/route.ts"]){const source=await readFile(path,"utf8");assert.match(source,/requireApiUser|requireRole/,path);assert.doesNotMatch(source,/body\.userId|body\.user_id/,path)}});
test("conversation reads and writes both require membership",async()=>{const source=await readFile("app/api/messages/route.ts","utf8");assert.ok((source.match(/conversationMembers\.userId,user\.id/g)||[]).length>=3);assert.match(source,/status:403/)});
test("orders ignore browser prices and totals",async()=>{const source=await readFile("app/api/orders/route.ts","utf8");assert.doesNotMatch(source,/body\.(price|subtotal|discount|deliveryFee|total)/);assert.match(source,/product\.price/);assert.match(source,/coupon\.discountValue/)});
test("account deletion revokes sessions without deleting accounting history",async()=>{const source=await readFile("app/api/account/route.ts","utf8");assert.match(source,/status: "deleted"/);assert.match(source,/revokedAt/);assert.doesNotMatch(source,/delete\(profiles\)/)});
