import { and, eq, isNull } from "drizzle-orm";
import { getDb } from "../../../db";
import { products, stores } from "../../../db/pg-schema";
import { requireApiUser } from "../../lib/authz";

async function ownedProduct(userId:string,productId:string){const db=getDb();return db.select({id:products.id}).from(products).innerJoin(stores,eq(stores.id,products.storeId)).where(and(eq(products.id,productId),eq(stores.ownerId,userId),isNull(products.deletedAt),isNull(stores.deletedAt))).limit(1)}
export async function POST(request:Request){try{const user=await requireApiUser();const body=await request.json() as Record<string,unknown>;const storeId=String(body.storeId??"");const db=getDb();const owned=await db.select({id:stores.id}).from(stores).where(and(eq(stores.id,storeId),eq(stores.ownerId,user.id),isNull(stores.deletedAt))).limit(1);if(!owned.length)return Response.json({error:"المتجر غير موجود أو لا تملكه"},{status:403});const name=String(body.name??"").trim(),price=Number(body.price),stock=Number(body.stock??0);if(name.length<2||!Number.isFinite(price)||price<0||!Number.isInteger(stock)||stock<0)return Response.json({error:"بيانات المنتج غير صحيحة"},{status:400});const id=crypto.randomUUID(),slug=`${name.toLowerCase().replace(/[^\p{L}\p{N}]+/gu,"-")}-${id.slice(0,6)}`;const [product]=await db.insert(products).values({id,storeId,name,slug,price,stock,unit:String(body.unit??"قطعة")}).returning();return Response.json({product},{status:201})}catch(error){if(error instanceof Response)return error;return Response.json({error:"تعذر إضافة المنتج"},{status:500})}}
export async function PATCH(request:Request){try{const user=await requireApiUser(),body=await request.json() as Record<string,unknown>,id=String(body.id??"");if(!id)return Response.json({error:"المنتج مطلوب"},{status:400});if(!(await ownedProduct(user.id,id)).length)return Response.json({error:"لا تملك هذا المنتج"},{status:403});const updates:Record<string,unknown>={updatedAt:new Date()};if(body.name!==undefined){const name=String(body.name).trim();if(name.length<2)return Response.json({error:"اسم المنتج غير صالح"},{status:400});updates.name=name}if(body.price!==undefined){const price=Number(body.price);if(!Number.isFinite(price)||price<0)return Response.json({error:"السعر غير صالح"},{status:400});updates.price=price}if(body.stock!==undefined){const stock=Number(body.stock);if(!Number.isInteger(stock)||stock<0)return Response.json({error:"المخزون غير صالح"},{status:400});updates.stock=stock}if(body.unit!==undefined)updates.unit=String(body.unit);if(body.active!==undefined)updates.active=Boolean(body.active);const [product]=await getDb().update(products).set(updates).where(eq(products.id,id)).returning();return Response.json({product})}catch(error){if(error instanceof Response)return error;return Response.json({error:"تعذر تعديل المنتج"},{status:500})}}
export async function DELETE(request:Request){try{const user=await requireApiUser(),id=new URL(request.url).searchParams.get("id")??"";if(!id)return Response.json({error:"المنتج مطلوب"},{status:400});if(!(await ownedProduct(user.id,id)).length)return Response.json({error:"لا تملك هذا المنتج"},{status:403});await getDb().update(products).set({active:false,deletedAt:new Date(),updatedAt:new Date()}).where(eq(products.id,id));return Response.json({ok:true})}catch(error){if(error instanceof Response)return error;return Response.json({error:"تعذر أرشفة المنتج"},{status:500})}}
