import { and, eq, gte, isNull, lte, sql } from "drizzle-orm";
import { getDb } from "../../../db";
import { couponRedemptions, coupons, offers, stores } from "../../../db/pg-schema";
import { requireApiUser } from "../../lib/authz";
type DiscountInput={storeId?:string;code?:string;subtotal?:number};
function discount(type:"percentage"|"fixed",value:number,subtotal:number,max:number|null){const raw=type==="percentage"?subtotal*(value/100):value;return Math.max(0,Math.min(subtotal,max===null?raw:Math.min(raw,max)))}
export async function POST(request:Request){try{const user=await requireApiUser(),body=await request.json() as DiscountInput;if(!body.storeId||!body.code||!Number.isFinite(Number(body.subtotal))||Number(body.subtotal)<0)return Response.json({error:"بيانات الكوبون غير صالحة"},{status:400});const db=getDb(),now=new Date(),[coupon]=await db.select().from(coupons).where(and(eq(coupons.storeId,body.storeId),eq(coupons.code,body.code.trim().toUpperCase()),eq(coupons.active,true),lte(coupons.startsAt,now),gte(coupons.endsAt,now),isNull(coupons.deletedAt))).limit(1);if(!coupon)return Response.json({error:"الكوبون غير صالح أو منتهي"},{status:404});const subtotal=Number(body.subtotal);if(subtotal<coupon.minimumOrder)return Response.json({error:`الحد الأدنى للطلب ${coupon.minimumOrder} ج`},{status:409});const [{count:totalUses}]=await db.select({count:sql<number>`count(*)`}).from(couponRedemptions).where(eq(couponRedemptions.couponId,coupon.id)),[{count:userUses}]=await db.select({count:sql<number>`count(*)`}).from(couponRedemptions).where(and(eq(couponRedemptions.couponId,coupon.id),eq(couponRedemptions.userId,user.id)));if(coupon.usageLimit!==null&&totalUses>=coupon.usageLimit)return Response.json({error:"تم استنفاد الكوبون"},{status:409});if(userUses>=coupon.perUserLimit)return Response.json({error:"وصلت للحد المسموح لهذا الكوبون"},{status:409});const amount=discount(coupon.discountType,coupon.discountValue,subtotal,coupon.maximumDiscount);return Response.json({couponId:coupon.id,discount:amount,total:subtotal-amount})}catch(e){if(e instanceof Response)return e;return Response.json({error:"تعذر التحقق من الكوبون"},{status:500})}}
export async function PUT(request:Request){try{const user=await requireApiUser(),body=await request.json() as Record<string,unknown>,storeId=String(body.storeId??""),db=getDb(),owned=await db.select({id:stores.id}).from(stores).where(and(eq(stores.id,storeId),eq(stores.ownerId,user.id))).limit(1);if(!owned.length)return Response.json({error:"لا تملك هذا المتجر"},{status:403});const code=String(body.code??"").trim().toUpperCase(),type=String(body.discountType),value=Number(body.discountValue),start=new Date(String(body.startsAt)),end=new Date(String(body.endsAt));if(code.length<3||!(["percentage","fixed"] as string[]).includes(type)||!Number.isFinite(value)||value<=0||(type==="percentage"&&value>100)||Number.isNaN(start.getTime())||end<=start)return Response.json({error:"بيانات الكوبون غير صالحة"},{status:400});const [row]=await db.insert(coupons).values({id:crypto.randomUUID(),storeId,code,discountType:type as "percentage"|"fixed",discountValue:value,minimumOrder:Number(body.minimumOrder)||0,maximumDiscount:body.maximumDiscount?Number(body.maximumDiscount):null,usageLimit:body.usageLimit?Number(body.usageLimit):null,perUserLimit:Number(body.perUserLimit)||1,startsAt:start,endsAt:end}).returning();return Response.json({coupon:row},{status:201})}catch(e){if(e instanceof Response)return e;return Response.json({error:"تعذر إنشاء الكوبون"},{status:500})}}
export async function GET(request:Request){const storeId=new URL(request.url).searchParams.get("storeId"),db=getDb(),now=new Date();if(!storeId)return Response.json({offers:[]});const rows=await db.select().from(offers).where(and(eq(offers.storeId,storeId),eq(offers.status,"active"),lte(offers.startsAt,now),gte(offers.endsAt,now),isNull(offers.deletedAt)));return Response.json({offers:rows})}
