import { and, desc, eq, isNull } from "drizzle-orm";
import Link from "next/link";
import { getDb } from "../db";
import { listings, products, serviceProfiles, stores, systemSettings } from "../db/pg-schema";

async function loadHome(){try{const db=getDb();const [storeRows,productRows,serviceRows,listingRows,settings]=await Promise.all([
db.select({id:stores.id,name:stores.name,description:stores.description,address:stores.address}).from(stores).where(and(eq(stores.status,"active"),isNull(stores.deletedAt))).orderBy(desc(stores.updatedAt)).limit(8),
db.select({id:products.id,name:products.name,price:products.price,stock:products.stock,storeId:products.storeId}).from(products).where(and(eq(products.active,true),isNull(products.deletedAt))).orderBy(desc(products.updatedAt)).limit(8),
db.select({id:serviceProfiles.id,name:serviceProfiles.name,profession:serviceProfiles.profession,description:serviceProfiles.description}).from(serviceProfiles).where(and(eq(serviceProfiles.status,"active"),isNull(serviceProfiles.deletedAt))).orderBy(desc(serviceProfiles.updatedAt)).limit(6),
db.select({id:listings.id,title:listings.title,kind:listings.kind,price:listings.price}).from(listings).where(and(eq(listings.status,"active"),isNull(listings.deletedAt))).orderBy(desc(listings.updatedAt)).limit(6),
db.select({key:systemSettings.key,value:systemSettings.value}).from(systemSettings),
]);return{storeRows,productRows,serviceRows,listingRows,settings:Object.fromEntries(settings.map(x=>[x.key,x.value]))}}catch{return{storeRows:[],productRows:[],serviceRows:[],listingRows:[],settings:{}}}}

export default async function Home(){const data=await loadHome();const trialDays=Number(data.settings.merchant_trial_days||30),subscriptionPrice=Number(data.settings.merchant_monthly_price_egp||149);return <main>
<div className="announcement">ديرب أونلاين — دليلك وخدماتك المحلية في مكان واحد</div>
<header className="site-header"><Link className="brand" href="/"><span className="brand-mark">د</span><span><strong>ديرب</strong><small>ديرب نجم كلها في موبايلك</small></span></Link><nav><Link href="/market">المنتجات</Link><Link href="/services">الخدمات</Link><Link href="/ask">اسأل أهل ديرب</Link><Link href="/community">المجتمع</Link><Link href="/listings">الإعلانات</Link><Link href="/search">البحث</Link></nav><div className="header-actions"><Link className="ghost" href="/login">دخول</Link><Link className="ghost" href="/register">حساب جديد</Link><Link className="primary" href="/business">سجّل نشاطك</Link></div></header>
<section className="hero" id="top"><div className="hero-copy"><span className="eyebrow">📍 ديرب نجم، الشرقية</span><h1>كل اللي محتاجه في ديرب<br/><em>أقرب مما تتخيّل</em></h1><p>ابحث في المتاجر والمنتجات والخدمات والإعلانات المنشورة فعليًا.</p><form className="search-box" action="/search"><span>⌕</span><input name="q" minLength={2} placeholder="بتدور على إيه في ديرب؟" aria-label="البحث في ديرب"/><button>ابحث</button></form></div><div className="hero-visual" aria-hidden="true"><div className="map-ring ring-one"/><div className="map-ring ring-two"/><div className="phone-card"><div className="phone-top"><span>أهلًا يا ديرب 👋</span></div><div className="mini-search">⌕ ابحث قريب منك</div><div className="phone-grid"><span>🛒<small>متاجر</small></span><span>🛠️<small>خدمات</small></span><span>📌<small>إعلانات</small></span></div></div></div></section>
<section className="stats"><div><b>{data.storeRows.length}</b><span>متجر ظاهر</span></div><div><b>{data.productRows.length}</b><span>منتج حديث</span></div><div><b>{data.serviceRows.length}</b><span>مقدم خدمة</span></div><div><b>{data.listingRows.length}</b><span>إعلان حديث</span></div></section>
<section className="section soft"><div className="section-heading"><div><span className="kicker">من قاعدة البيانات</span><h2>متاجر نشطة</h2></div><Link className="text-button" href="/market">عرض السوق ←</Link></div>{data.storeRows.length===0?<div className="empty"><span>🏪</span><h3>لا توجد متاجر منشورة بعد</h3><p>ستظهر المتاجر هنا بعد اعتمادها من الإدارة.</p></div>:<div className="store-grid">{data.storeRows.map(s=><article className="store-card" key={s.id}><div className="store-cover"><span>🏪</span></div><div className="store-body"><h3>{s.name}</h3><p>{s.description||s.address}</p></div></article>)}</div>}</section>
<section className="section"><div className="section-heading"><div><span className="kicker">خدمات معتمدة</span><h2>مقدمو الخدمات</h2></div><Link className="text-button" href="/services">عرض الخدمات ←</Link></div>{data.serviceRows.length===0?<div className="empty"><span>🛠️</span><h3>لا توجد خدمات منشورة بعد</h3></div>:<div className="service-grid">{data.serviceRows.map(s=><article className="service-card" key={s.id}><span className="avatar">🛠️</span><div><h3>{s.name}</h3><b>{s.profession}</b><p>{s.description}</p></div></article>)}</div>}</section>
<section className="business"><div><span className="business-icon">🏪</span><div><span className="kicker light">لأصحاب الأنشطة</span><h2>اعرض نشاطك لأهل ديرب</h2><p>فترة التجربة وسعر الاشتراك يأتيان من إعدادات النظام ويمكن للإدارة تحديثهما.</p><Link className="business-cta" href="/business">ابدأ إدارة نشاطك</Link></div></div><div className="business-numbers"><span><b>{trialDays}</b> يوم تجربة</span><span><b>{subscriptionPrice}</b> جنيه/شهر</span></div></section>
<footer><div className="brand footer-brand"><span className="brand-mark">د</span><strong>ديرب</strong></div><p>منصة محلية تجمع أهل ديرب نجم بأنشطتها وخدماتها.</p><div><Link href="/support">الدعم</Link><Link href="/account">الحساب</Link><Link href="/notifications">الإشعارات</Link></div></footer>
<nav className="mobile-nav"><Link href="/">⌂<small>الرئيسية</small></Link><Link href="/search">⌕<small>البحث</small></Link><Link href="/market">🛒<small>السوق</small></Link><Link href="/notifications">♢<small>الإشعارات</small></Link><Link href="/account">♙<small>حسابي</small></Link></nav>
</main>}
