import { and, desc, eq, isNull } from "drizzle-orm";
import Link from "next/link";
import { getDb } from "../db";
import { listings, products, serviceProfiles, stores, systemSettings } from "../db/pg-schema";

async function loadHome(){try{const db=getDb();const [storeRows,productRows,serviceRows,listingRows,settings]=await Promise.all([
 db.select({id:stores.id,name:stores.name,description:stores.description,address:stores.address}).from(stores).where(and(eq(stores.status,"active"),isNull(stores.deletedAt))).orderBy(desc(stores.updatedAt)).limit(8),
 db.select({id:products.id,name:products.name,price:products.price,stock:products.stock,storeId:products.storeId}).from(products).where(and(eq(products.active,true),isNull(products.deletedAt))).orderBy(desc(products.updatedAt)).limit(8),
 db.select({id:serviceProfiles.id,name:serviceProfiles.name,profession:serviceProfiles.profession,description:serviceProfiles.description}).from(serviceProfiles).where(and(eq(serviceProfiles.status,"active"),isNull(serviceProfiles.deletedAt))).orderBy(desc(serviceProfiles.updatedAt)).limit(6),
 db.select({id:listings.id,title:listings.title,kind:listings.kind,price:listings.price}).from(listings).where(and(eq(listings.status,"active"),isNull(listings.deletedAt))).orderBy(desc(listings.updatedAt)).limit(8),
 db.select({key:systemSettings.key,value:systemSettings.value}).from(systemSettings),
 ]);return{storeRows,productRows,serviceRows,listingRows,settings:Object.fromEntries(settings.map(x=>[x.key,x.value]))}}catch{return{storeRows:[],productRows:[],serviceRows:[],listingRows:[],settings:{}}}}
const sections=[
 {href:"/directory",icon:"📍",title:"دليل ديرب",small:"القرى والأنشطة"},{href:"/market",icon:"🛒",title:"السوق",small:"متاجر ومنتجات"},{href:"/services",icon:"🛠️",title:"الخدمات",small:"مهنيون ومقدمو خدمة"},{href:"/ask",icon:"❓",title:"اسأل أهل ديرب",small:"اسأل وخد إجابة"},{href:"/community",icon:"👥",title:"المجتمع",small:"منشورات أهل البلد"},{href:"/cars",icon:"🚗",title:"السيارات",small:"بيع وشراء"},{href:"/real-estate",icon:"🏠",title:"العقارات",small:"بيع وإيجار"},{href:"/jobs",icon:"💼",title:"الوظائف",small:"فرص عمل محلية"},
];
const routeForKind=(kind:string)=>kind==="car"?"/cars":kind==="property"?"/real-estate":kind==="job"?"/jobs":"/listings";

export default async function Home(){const data=await loadHome();const trialDays=Number(data.settings.merchant_trial_days||30),subscriptionPrice=Number(data.settings.merchant_monthly_price_egp||149);return <main>
 <div className="announcement">ديرب أونلاين — ديرب نجم كلها في موبايلك</div>
 <header className="site-header"><Link className="brand" href="/"><span className="brand-mark">د</span><span><strong>ديرب</strong><small>ديرب نجم كلها في موبايلك</small></span></Link><nav><Link href="/directory">دليل ديرب</Link><Link href="/market">السوق</Link><Link href="/services">الخدمات</Link><Link href="/ask">اسأل أهل ديرب</Link><Link href="/community">المجتمع</Link><Link href="/search">البحث</Link></nav><div className="header-actions"><Link className="ghost" href="/login">دخول</Link><Link className="ghost" href="/register">حساب جديد</Link><Link className="primary" href="/business">سجّل نشاطك</Link></div></header>
 <section className="hero" id="top"><div className="hero-copy"><span className="eyebrow">📍 مدينة وقرى مركز ديرب نجم، الشرقية</span><h1>كل اللي محتاجه في ديرب<br/><em>في مكان واحد</em></h1><p>دليل محلي، سوق، خدمات، أسئلة أهل البلد، سيارات، عقارات، وظائف وإعلانات — بداتا حقيقية من المنصة.</p><form className="search-box" action="/search"><span>⌕</span><input name="q" minLength={2} placeholder="محل، دكتور، منتج، وظيفة، عربية، شقة..." aria-label="البحث في ديرب"/><button>ابحث</button></form><div className="quick"><span>أقسام سريعة:</span><Link href="/directory">دليل القرى</Link><Link href="/cars">سيارات</Link><Link href="/real-estate">عقارات</Link><Link href="/jobs">وظائف</Link></div></div><div className="hero-visual" aria-hidden="true"><div className="map-ring ring-one"/><div className="map-ring ring-two"/><div className="phone-card"><div className="phone-top"><span>أهلًا يا ديرب 👋</span></div><div className="mini-search">⌕ ابحث قريب منك</div><div className="phone-grid"><span>🏪<small>متاجر</small></span><span>🛠️<small>خدمات</small></span><span>📍<small>دليل</small></span></div></div></div></section>
 <section className="stats"><div><b>{data.storeRows.length}</b><span>متجر ظاهر</span></div><div><b>{data.productRows.length}</b><span>منتج حديث</span></div><div><b>{data.serviceRows.length}</b><span>مقدم خدمة</span></div><div><b>{data.listingRows.length}</b><span>إعلان حديث</span></div></section>
 <section className="section"><div className="section-heading"><div><span className="kicker">ديرب كلها</span><h2>اختار اللي محتاجه</h2></div></div><div className="category-grid">{sections.map(x=><Link className="category" href={x.href} key={x.href}><span>{x.icon}</span><b>{x.title}</b><small>{x.small}</small></Link>)}</div></section>
 <section className="section soft"><div className="section-heading"><div><span className="kicker">من قاعدة البيانات</span><h2>متاجر نشطة</h2></div><Link className="text-button" href="/market">عرض السوق ←</Link></div>{data.storeRows.length===0?<div className="empty"><span>🏪</span><h3>لا توجد متاجر منشورة بعد</h3><p>ستظهر المتاجر هنا بعد اعتمادها من الإدارة.</p></div>:<div className="store-grid">{data.storeRows.map(s=><article className="store-card" key={s.id}><div className="store-cover"><span>🏪</span></div><div className="store-body"><h3>{s.name}</h3><p>{s.description||s.address}</p><Link className="wide-button" href="/market">عرض المنتجات</Link></div></article>)}</div>}</section>
 <section className="section"><div className="section-heading"><div><span className="kicker">منتجات حديثة</span><h2>من سوق ديرب</h2></div><Link className="text-button" href="/market">كل المنتجات ←</Link></div>{data.productRows.length===0?<div className="empty"><span>🛒</span><h3>لا توجد منتجات منشورة بعد</h3></div>:<div className="store-grid">{data.productRows.map(p=><article className="store-card" key={p.id}><div className="store-cover"><span>🛍️</span></div><div className="store-body"><h3>{p.name}</h3><p>{p.stock>0?`${p.stock} متاح في المخزون`:"غير متاح حاليًا"}</p><strong>{p.price.toLocaleString("ar-EG")} ج</strong></div></article>)}</div>}</section>
 <section className="section soft"><div className="section-heading"><div><span className="kicker">إعلانات أهل ديرب</span><h2>الأحدث</h2></div><Link className="text-button" href="/listings">كل الإعلانات ←</Link></div>{data.listingRows.length===0?<div className="empty"><span>📌</span><h3>لا توجد إعلانات منشورة بعد</h3></div>:<div className="service-grid">{data.listingRows.map(x=><Link className="service-card" href={routeForKind(x.kind)} key={x.id}><span className="avatar">{x.kind==="car"?"🚗":x.kind==="property"?"🏠":x.kind==="job"?"💼":"📌"}</span><div><h3>{x.title}</h3>{x.price!==null&&<b>{x.price.toLocaleString("ar-EG")} ج</b>}<small>فتح القسم</small></div></Link>)}</div>}</section>
 <section className="section"><div className="section-heading"><div><span className="kicker">خدمات معتمدة</span><h2>مقدمو الخدمات</h2></div><Link className="text-button" href="/services">عرض الخدمات ←</Link></div>{data.serviceRows.length===0?<div className="empty"><span>🛠️</span><h3>لا توجد خدمات منشورة بعد</h3></div>:<div className="service-grid">{data.serviceRows.map(s=><article className="service-card" key={s.id}><span className="avatar">🛠️</span><div><h3>{s.name}</h3><b>{s.profession}</b><p>{s.description}</p></div></article>)}</div>}</section>
 <section className="business"><div><span className="business-icon">🏪</span><div><span className="kicker light">لأصحاب الأنشطة</span><h2>اعرض نشاطك لأهل ديرب</h2><p>ابدأ التجربة، أضف منتجاتك، استقبل الطلبات وتابع نشاطك من لوحة ديرب بيزنس.</p><Link className="business-cta" href="/business">ابدأ إدارة نشاطك</Link></div></div><div className="business-numbers"><span><b>{trialDays}</b> يوم تجربة</span><span><b>{subscriptionPrice}</b> جنيه/شهر</span></div></section>
 <footer><div className="brand footer-brand"><span className="brand-mark">د</span><strong>ديرب</strong></div><p>منصة محلية تجمع أهل ديرب نجم بأنشطتها وخدماتها وأسواقها.</p><div><Link href="/directory">دليل ديرب</Link><Link href="/support">الدعم</Link><Link href="/privacy">الخصوصية</Link><Link href="/account">الحساب</Link></div></footer>
 <nav className="mobile-nav"><Link href="/">⌂<small>الرئيسية</small></Link><Link href="/directory">⌖<small>الدليل</small></Link><Link href="/search">⌕<small>البحث</small></Link><Link href="/market">🛒<small>السوق</small></Link><Link href="/account">♙<small>حسابي</small></Link></nav>
 </main>}
