"use client";

import { useMemo, useState } from "react";

const categories = [["🍽️","مطاعم"],["🛒","سوبر ماركت"],["💊","صيدليات"],["🩺","أطباء"],["🛠️","صنايعية"],["🏠","عقارات"],["🚗","سيارات"],["💼","وظائف"]];
const stores = [
 {name:"ماركت البلد",category:"سوبر ماركت",area:"ديرب البلد",rating:"4.8",time:"25–35 دقيقة",icon:"🛒",color:"#e8f6ee",offer:"خصم 10%"},
 {name:"صيدلية النور",category:"صيدليات",area:"شارع النصر",rating:"4.9",time:"مفتوح 24 ساعة",icon:"💊",color:"#e8f1ff",offer:"توصيل مجاني"},
 {name:"كشري الديرباوي",category:"مطاعم",area:"ميدان المحطة",rating:"4.7",time:"20–30 دقيقة",icon:"🍲",color:"#fff2da",offer:"وجبة اليوم"},
 {name:"مركز د. أحمد",category:"أطباء",area:"شارع المركز",rating:"4.9",time:"الحجز متاح",icon:"🩺",color:"#f1ecff",offer:"كشف اليوم"},
];
const services = [
 {name:"محمد السيد",job:"كهربائي منازل",area:"ديرب نجم والقرى",rating:"4.8",icon:"⚡"},
 {name:"ورشة الأمانة",job:"سباكة وصيانة",area:"الصانية • صافور",rating:"4.7",icon:"🔧"},
 {name:"نقل ديرب",job:"نقل أثاث وبضائع",area:"جميع قرى المركز",rating:"4.9",icon:"🚚"},
];

export default function Home(){
 const [query,setQuery]=useState(""); const [active,setActive]=useState("الكل"); const [saved,setSaved]=useState<string[]>([]);
 const filtered=useMemo(()=>stores.filter(s=>(active==="الكل"||s.category===active)&&`${s.name} ${s.category} ${s.area}`.includes(query.trim())),[active,query]);
 const save=(name:string)=>setSaved(x=>x.includes(name)?x.filter(v=>v!==name):[...x,name]);
 return <main>
  <div className="announcement">تجربة ديرب الأولى قيد التطوير — سجّل نشاطك مجانًا لمدة 30 يومًا</div>
  <header className="site-header"><a className="brand" href="#top"><span className="brand-mark">د</span><span><strong>ديرب</strong><small>ديرب نجم كلها في موبايلك</small></span></a><nav><a href="/market">المتاجر</a><a href="/services">الخدمات</a><a href="/community">المجتمع</a><a href="/listings">الإعلانات</a></nav><div className="header-actions"><a className="ghost" href="/ask">اسأل درب</a><a className="primary" href="/business">سجّل نشاطك</a></div></header>
  <section className="hero" id="top"><div className="hero-copy"><span className="eyebrow">📍 ديرب نجم، الشرقية</span><h1>كل اللي محتاجه في ديرب<br/><em>أقرب مما تتخيّل</em></h1><p>محلات، مطاعم، صيدليات، دكاترة، صنايعية وخدمات بلدك كلها في مكان واحد.</p><div className="search-box"><span>⌕</span><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="بتدور على إيه في ديرب؟" aria-label="البحث في ديرب"/><button onClick={()=>document.querySelector("#stores")?.scrollIntoView({behavior:"smooth"})}>ابحث</button></div><div className="quick"><span>الأكثر بحثًا:</span><button onClick={()=>setQuery("صيدليات")}>صيدلية</button><button onClick={()=>setQuery("مطاعم")}>أكل</button><button onClick={()=>setActive("صنايعية")}>كهربائي</button></div></div>
  <div className="hero-visual" aria-hidden="true"><div className="map-ring ring-one"/><div className="map-ring ring-two"/><div className="phone-card"><div className="phone-top"><span>أهلًا يا ديرب 👋</span><b>●</b></div><div className="mini-search">⌕ ابحث قريب منك</div><div className="phone-grid"><span>🍔<small>مطاعم</small></span><span>💊<small>صيدليات</small></span><span>🔧<small>خدمات</small></span></div><div className="mini-store"><i>🛒</i><div><b>ماركت البلد</b><small>مفتوح الآن • 4.8 ★</small></div></div><div className="mini-store"><i>🍲</i><div><b>أكل بيتي</b><small>توصيل سريع • 4.7 ★</small></div></div></div><span className="float-chip chip-one">⚡ خدمات سريعة</span><span className="float-chip chip-two">⭐ الأعلى تقييمًا</span></div></section>
  <section className="stats"><div><b>+120</b><span>نشاط محلي</span></div><div><b>+32</b><span>قرية ومنطقة</span></div><div><b>24/7</b><span>دليل متاح</span></div><div><b>محلي 100%</b><span>مخصوص لديرب</span></div></section>
  <section className="section"><div className="section-heading"><div><span className="kicker">اكتشف ديرب</span><h2>إيه اللي محتاجه النهارده؟</h2></div><button className="text-button" onClick={()=>setActive("الكل")}>عرض الكل ←</button></div><div className="category-grid">{categories.map(([icon,label])=><button key={label} className={active===label?"category active":"category"} onClick={()=>{setActive(label);document.querySelector("#stores")?.scrollIntoView({behavior:"smooth"})}}><span>{icon}</span><b>{label}</b><small>استكشف الآن</small></button>)}</div></section>
  <section className="section soft" id="stores"><div className="section-heading"><div><span className="kicker">اختيارات أهل البلد</span><h2>أنشطة مميزة قريب منك</h2></div><div className="filter-pills"><button className={active==="الكل"?"active":""} onClick={()=>setActive("الكل")}>الكل</button><button onClick={()=>setActive("مطاعم")}>مطاعم</button><button onClick={()=>setActive("صيدليات")}>صيدليات</button></div></div>{filtered.length?<div className="store-grid">{filtered.map(s=><article className="store-card" key={s.name}><div className="store-cover" style={{background:s.color}}><span>{s.icon}</span><label>{s.offer}</label><button onClick={()=>save(s.name)} aria-label={`حفظ ${s.name}`}>{saved.includes(s.name)?"♥":"♡"}</button></div><div className="store-body"><div className="store-title"><div><h3>{s.name}</h3><p>{s.category} • {s.area}</p></div><span>موثّق ✓</span></div><div className="store-meta"><b>★ {s.rating}</b><span>{s.time}</span></div><button className="wide-button">عرض التفاصيل</button></div></article>)}</div>:<div className="empty"><span>🔎</span><h3>مفيش نتيجة مطابقة</h3><p>جرّب اسم نشاط أو تصنيف مختلف.</p><button onClick={()=>{setQuery("");setActive("الكل")}}>مسح البحث</button></div>}</section>
  <section className="section" id="services"><div className="section-heading"><div><span className="kicker">ناس ثقة من بلدك</span><h2>خدمات وصنايعية</h2></div><a className="text-button" href="#top">اطلب خدمة ←</a></div><div className="service-grid">{services.map(s=><article className="service-card" key={s.name}><span className="avatar">{s.icon}</span><div><h3>{s.name}</h3><b>{s.job}</b><p>📍 {s.area}</p><small>★ {s.rating} • متاح اليوم</small></div><div className="contact-buttons"><button aria-label="اتصال">☎</button><button aria-label="واتساب">◉</button></div></article>)}</div></section>
  <section className="business" id="offers"><div><span className="business-icon">🏪</span><div><span className="kicker light">لأصحاب الأنشطة في ديرب</span><h2>كبّر شغلك وخلي أهل ديرب يوصلولك</h2><p>أنشئ صفحة لنشاطك، اعرض منتجاتك واستقبل طلباتك. أول 30 يوم مجانًا، وبعدها تبدأ الخطط من 149 جنيه شهريًا.</p><a className="business-cta" href="/business">ابدأ تجربتك المجانية</a><small>بدون دفع مقدم • تقدر تلغي في أي وقت</small></div></div><div className="business-numbers"><span><b>30</b> يوم مجانًا</span><span><b>149</b> جنيه/شهر</span><span><b>∞</b> فرص وصول</span></div></section>
  <footer><div className="brand footer-brand"><span className="brand-mark">د</span><span><strong>ديرب</strong><small>ديرب نجم كلها في موبايلك</small></span></div><p>منصة محلية تجمع أهل ديرب نجم بأنشطتها وخدماتها.</p><div><a href="#">من نحن</a><a href="#">الخصوصية</a><a href="#">الشروط</a><a href="#">تواصل معنا</a></div><small>© 2026 ديرب. نسخة تجريبية قيد التطوير.</small></footer>
  <nav className="mobile-nav"><a href="#top">⌂<small>الرئيسية</small></a><a href="#stores">⌕<small>استكشف</small></a><button>＋<small>اطلب</small></button><a href="#offers">♢<small>العروض</small></a><a href="#">♙<small>حسابي</small></a></nav>
 </main>
}
