import { sql } from "drizzle-orm";
import { boolean, check, doublePrecision, index, integer, pgTable, text, timestamp, uniqueIndex } from "drizzle-orm/pg-core";
const time = { createdAt: timestamp("created_at",{withTimezone:true}).notNull().$defaultFn(()=>new Date()), updatedAt: timestamp("updated_at",{withTimezone:true}).notNull().$defaultFn(()=>new Date()), deletedAt: timestamp("deleted_at",{withTimezone:true}) };

export const profiles=pgTable("profiles",{id:text("id").primaryKey(),email:text("email").notNull(),fullName:text("full_name"),phone:text("phone"),avatarKey:text("avatar_key"),status:text("status",{enum:["active","suspended","deleted"]}).notNull().default("active"),...time},t=>[uniqueIndex("profiles_email_uq").on(t.email),check("profiles_status_check",sql`${t.status} in ('active','suspended','deleted')`)]);
export const userRoles=pgTable("user_roles",{id:text("id").primaryKey(),userId:text("user_id").notNull().references(()=>profiles.id,{onDelete:"cascade"}),role:text("role",{enum:["customer","merchant","service_provider","delivery","staff","moderator","admin","super_admin"]}).notNull(),createdAt:timestamp("created_at",{withTimezone:true}).notNull().$defaultFn(()=>new Date())},t=>[uniqueIndex("user_roles_user_role_uq").on(t.userId,t.role),index("user_roles_user_idx").on(t.userId),check("user_roles_role_check",sql`${t.role} in ('customer','merchant','service_provider','delivery','staff','moderator','admin','super_admin')`)]);
export const locations=pgTable("locations",{id:text("id").primaryKey(),parentId:text("parent_id"),type:text("type",{enum:["governorate","center","city","village","district","street"]}).notNull(),nameAr:text("name_ar").notNull(),slug:text("slug").notNull(),active:boolean("active").notNull().default(true),sortOrder:integer("sort_order").notNull().default(0),...time},t=>[uniqueIndex("locations_parent_slug_uq").on(t.parentId,t.slug),index("locations_parent_idx").on(t.parentId)]);
export const categories=pgTable("categories",{id:text("id").primaryKey(),parentId:text("parent_id"),nameAr:text("name_ar").notNull(),slug:text("slug").notNull(),icon:text("icon"),entityType:text("entity_type",{enum:["store","product","service","listing","job"]}).notNull(),active:boolean("active").notNull().default(true),sortOrder:integer("sort_order").notNull().default(0),...time},t=>[uniqueIndex("categories_type_slug_uq").on(t.entityType,t.slug)]);
export const stores=pgTable("stores",{id:text("id").primaryKey(),ownerId:text("owner_id").notNull().references(()=>profiles.id),categoryId:text("category_id").references(()=>categories.id),locationId:text("location_id").references(()=>locations.id),name:text("name").notNull(),slug:text("slug").notNull(),description:text("description"),phone:text("phone").notNull(),whatsapp:text("whatsapp"),address:text("address").notNull(),latitude:doublePrecision("latitude"),longitude:doublePrecision("longitude"),logoKey:text("logo_key"),coverKey:text("cover_key"),deliveryEnabled:boolean("delivery_enabled").notNull().default(false),minimumOrder:doublePrecision("minimum_order").notNull().default(0),deliveryFee:doublePrecision("delivery_fee").notNull().default(0),status:text("status",{enum:["draft","pending","active","suspended","rejected"]}).notNull().default("pending"),verified:boolean("verified").notNull().default(false),featured:boolean("featured").notNull().default(false),...time},t=>[uniqueIndex("stores_slug_uq").on(t.slug),index("stores_owner_idx").on(t.ownerId),index("stores_status_location_idx").on(t.status,t.locationId)]);
export const products=pgTable("products",{id:text("id").primaryKey(),storeId:text("store_id").notNull().references(()=>stores.id,{onDelete:"cascade"}),categoryId:text("category_id").references(()=>categories.id),name:text("name").notNull(),slug:text("slug").notNull(),description:text("description"),sku:text("sku"),price:doublePrecision("price").notNull(),compareAtPrice:doublePrecision("compare_at_price"),stock:integer("stock").notNull().default(0),unit:text("unit").notNull().default("قطعة"),active:boolean("active").notNull().default(true),featured:boolean("featured").notNull().default(false),sponsored:boolean("sponsored").notNull().default(false),...time},t=>[uniqueIndex("products_store_slug_uq").on(t.storeId,t.slug),index("products_store_active_idx").on(t.storeId,t.active)]);
export const addresses=pgTable("addresses",{id:text("id").primaryKey(),userId:text("user_id").notNull().references(()=>profiles.id,{onDelete:"cascade"}),locationId:text("location_id").references(()=>locations.id),label:text("label").notNull(),street:text("street").notNull(),building:text("building"),floor:text("floor"),apartment:text("apartment"),landmark:text("landmark"),notes:text("notes"),latitude:doublePrecision("latitude"),longitude:doublePrecision("longitude"),isDefault:boolean("is_default").notNull().default(false),...time},t=>[index("addresses_user_idx").on(t.userId)]);
export const orders=pgTable("orders",{id:text("id").primaryKey(),orderNumber:text("order_number").notNull(),customerId:text("customer_id").notNull().references(()=>profiles.id),storeId:text("store_id").notNull().references(()=>stores.id),addressId:text("address_id").references(()=>addresses.id),status:text("status",{enum:["pending","confirmed","preparing","ready","out_for_delivery","delivered","cancelled","rejected","refunded"]}).notNull().default("pending"),subtotal:doublePrecision("subtotal").notNull(),discount:doublePrecision("discount").notNull().default(0),deliveryFee:doublePrecision("delivery_fee").notNull().default(0),total:doublePrecision("total").notNull(),notes:text("notes"),...time},t=>[uniqueIndex("orders_number_uq").on(t.orderNumber),index("orders_customer_idx").on(t.customerId),index("orders_store_status_idx").on(t.storeId,t.status)]);
export const orderItems=pgTable("order_items",{id:text("id").primaryKey(),orderId:text("order_id").notNull().references(()=>orders.id,{onDelete:"cascade"}),productId:text("product_id").notNull().references(()=>products.id),nameSnapshot:text("name_snapshot").notNull(),unitPrice:doublePrecision("unit_price").notNull(),quantity:integer("quantity").notNull(),lineTotal:doublePrecision("line_total").notNull()},t=>[index("order_items_order_idx").on(t.orderId)]);
export const orderStatusHistory=pgTable("order_status_history",{id:text("id").primaryKey(),orderId:text("order_id").notNull().references(()=>orders.id,{onDelete:"cascade"}),fromStatus:text("from_status"),toStatus:text("to_status").notNull(),changedBy:text("changed_by").notNull().references(()=>profiles.id),note:text("note"),createdAt:timestamp("created_at",{withTimezone:true}).notNull().$defaultFn(()=>new Date())},t=>[index("order_history_order_idx").on(t.orderId)]);
export const auditLogs=pgTable("audit_logs",{id:text("id").primaryKey(),actorId:text("actor_id").references(()=>profiles.id),action:text("action").notNull(),entityType:text("entity_type").notNull(),entityId:text("entity_id"),metadataJson:text("metadata_json"),createdAt:timestamp("created_at",{withTimezone:true}).notNull().$defaultFn(()=>new Date())},t=>[index("audit_logs_entity_idx").on(t.entityType,t.entityId)]);

export const carts=pgTable("carts",{id:text("id").primaryKey(),userId:text("user_id").notNull().references(()=>profiles.id,{onDelete:"cascade"}),storeId:text("store_id").notNull().references(()=>stores.id,{onDelete:"cascade"}),status:text("status",{enum:["active","converted","abandoned"]}).notNull().default("active"),...time},t=>[index("carts_user_status_idx").on(t.userId,t.status),uniqueIndex("carts_user_store_status_uq").on(t.userId,t.storeId,t.status)]);
export const cartItems=pgTable("cart_items",{id:text("id").primaryKey(),cartId:text("cart_id").notNull().references(()=>carts.id,{onDelete:"cascade"}),productId:text("product_id").notNull().references(()=>products.id,{onDelete:"cascade"}),quantity:integer("quantity").notNull().default(1),createdAt:timestamp("created_at",{withTimezone:true}).notNull().$defaultFn(()=>new Date()),updatedAt:timestamp("updated_at",{withTimezone:true}).notNull().$defaultFn(()=>new Date())},t=>[uniqueIndex("cart_items_cart_product_uq").on(t.cartId,t.productId)]);
export const inventoryMovements=pgTable("inventory_movements",{id:text("id").primaryKey(),productId:text("product_id").notNull().references(()=>products.id,{onDelete:"cascade"}),type:text("type",{enum:["opening","purchase","sale","return","adjustment","reservation","release"]}).notNull(),quantity:integer("quantity").notNull(),referenceType:text("reference_type"),referenceId:text("reference_id"),actorId:text("actor_id").references(()=>profiles.id),note:text("note"),createdAt:timestamp("created_at",{withTimezone:true}).notNull().$defaultFn(()=>new Date())},t=>[index("inventory_product_created_idx").on(t.productId,t.createdAt)]);
export const subscriptionPlans=pgTable("subscription_plans",{id:text("id").primaryKey(),code:text("code").notNull(),nameAr:text("name_ar").notNull(),price:doublePrecision("price").notNull(),durationDays:integer("duration_days").notNull(),trialDays:integer("trial_days").notNull().default(0),featuresJson:text("features_json").notNull().default("[]"),active:boolean("active").notNull().default(true),...time},t=>[uniqueIndex("subscription_plans_code_uq").on(t.code)]);
export const subscriptions=pgTable("subscriptions",{id:text("id").primaryKey(),storeId:text("store_id").notNull().references(()=>stores.id,{onDelete:"cascade"}),planId:text("plan_id").notNull().references(()=>subscriptionPlans.id),status:text("status",{enum:["trial","active","past_due","expired","cancelled"]}).notNull(),startsAt:timestamp("starts_at",{withTimezone:true}).notNull(),endsAt:timestamp("ends_at",{withTimezone:true}).notNull(),...time},t=>[index("subscriptions_store_status_idx").on(t.storeId,t.status)]);
export const notifications=pgTable("notifications",{id:text("id").primaryKey(),userId:text("user_id").notNull().references(()=>profiles.id,{onDelete:"cascade"}),type:text("type").notNull(),title:text("title").notNull(),body:text("body").notNull(),entityType:text("entity_type"),entityId:text("entity_id"),readAt:timestamp("read_at",{withTimezone:true}),createdAt:timestamp("created_at",{withTimezone:true}).notNull().$defaultFn(()=>new Date())},t=>[index("notifications_user_read_idx").on(t.userId,t.readAt)]);
export const notificationPreferences=pgTable("notification_preferences",{id:text("id").primaryKey(),userId:text("user_id").notNull().references(()=>profiles.id,{onDelete:"cascade"}),type:text("type").notNull(),inApp:boolean("in_app").notNull().default(true),email:boolean("email").notNull().default(false),updatedAt:timestamp("updated_at",{withTimezone:true}).notNull().$defaultFn(()=>new Date())},t=>[uniqueIndex("notification_preferences_user_type_uq").on(t.userId,t.type)]);

export const offers=pgTable("offers",{id:text("id").primaryKey(),storeId:text("store_id").notNull().references(()=>stores.id,{onDelete:"cascade"}),productId:text("product_id").references(()=>products.id,{onDelete:"cascade"}),categoryId:text("category_id").references(()=>categories.id),name:text("name").notNull(),scope:text("scope",{enum:["product","store","category","flash"]}).notNull(),discountType:text("discount_type",{enum:["percentage","fixed"]}).notNull(),discountValue:doublePrecision("discount_value").notNull(),minimumOrder:doublePrecision("minimum_order").notNull().default(0),maximumDiscount:doublePrecision("maximum_discount"),startsAt:timestamp("starts_at",{withTimezone:true}).notNull(),endsAt:timestamp("ends_at",{withTimezone:true}).notNull(),status:text("status",{enum:["draft","active","paused","expired"]}).notNull().default("draft"),...time},t=>[index("offers_store_status_dates_idx").on(t.storeId,t.status,t.startsAt,t.endsAt)]);
export const coupons=pgTable("coupons",{id:text("id").primaryKey(),storeId:text("store_id").notNull().references(()=>stores.id,{onDelete:"cascade"}),code:text("code").notNull(),discountType:text("discount_type",{enum:["percentage","fixed"]}).notNull(),discountValue:doublePrecision("discount_value").notNull(),minimumOrder:doublePrecision("minimum_order").notNull().default(0),maximumDiscount:doublePrecision("maximum_discount"),usageLimit:integer("usage_limit"),perUserLimit:integer("per_user_limit").notNull().default(1),startsAt:timestamp("starts_at",{withTimezone:true}).notNull(),endsAt:timestamp("ends_at",{withTimezone:true}).notNull(),active:boolean("active").notNull().default(true),...time},t=>[uniqueIndex("coupons_store_code_uq").on(t.storeId,t.code),index("coupons_store_dates_idx").on(t.storeId,t.active,t.startsAt,t.endsAt)]);
export const couponRedemptions=pgTable("coupon_redemptions",{id:text("id").primaryKey(),couponId:text("coupon_id").notNull().references(()=>coupons.id),userId:text("user_id").notNull().references(()=>profiles.id),orderId:text("order_id").references(()=>orders.id),discountAmount:doublePrecision("discount_amount").notNull(),createdAt:timestamp("created_at",{withTimezone:true}).notNull().$defaultFn(()=>new Date())},t=>[index("coupon_redemptions_coupon_user_idx").on(t.couponId,t.userId),uniqueIndex("coupon_redemptions_order_uq").on(t.orderId)]);

export const serviceProfiles=pgTable("service_profiles",{id:text("id").primaryKey(),ownerId:text("owner_id").notNull().references(()=>profiles.id),categoryId:text("category_id").references(()=>categories.id),locationId:text("location_id").references(()=>locations.id),name:text("name").notNull(),profession:text("profession").notNull(),description:text("description").notNull(),phone:text("phone").notNull(),whatsapp:text("whatsapp"),priceFrom:doublePrecision("price_from"),availability:text("availability"),status:text("status",{enum:["draft","pending","active","rejected","suspended"]}).notNull().default("pending"),verified:boolean("verified").notNull().default(false),...time},t=>[index("service_profiles_owner_idx").on(t.ownerId),index("service_profiles_status_location_idx").on(t.status,t.locationId)]);
export const serviceRequests=pgTable("service_requests",{id:text("id").primaryKey(),customerId:text("customer_id").notNull().references(()=>profiles.id),providerId:text("provider_id").notNull().references(()=>serviceProfiles.id),addressId:text("address_id").references(()=>addresses.id),details:text("details").notNull(),preferredAt:timestamp("preferred_at",{withTimezone:true}),status:text("status",{enum:["pending","accepted","in_progress","completed","cancelled","rejected"]}).notNull().default("pending"),...time},t=>[index("service_requests_customer_idx").on(t.customerId),index("service_requests_provider_status_idx").on(t.providerId,t.status)]);
export const reviews=pgTable("reviews",{id:text("id").primaryKey(),userId:text("user_id").notNull().references(()=>profiles.id),entityType:text("entity_type",{enum:["store","product","service"]}).notNull(),entityId:text("entity_id").notNull(),orderId:text("order_id").references(()=>orders.id),rating:integer("rating").notNull(),comment:text("comment"),status:text("status",{enum:["pending","published","hidden","reported"]}).notNull().default("published"),...time},t=>[uniqueIndex("reviews_user_entity_order_uq").on(t.userId,t.entityType,t.entityId,t.orderId),index("reviews_entity_status_idx").on(t.entityType,t.entityId,t.status)]);
export const favorites=pgTable("favorites",{id:text("id").primaryKey(),userId:text("user_id").notNull().references(()=>profiles.id,{onDelete:"cascade"}),entityType:text("entity_type",{enum:["store","product","service","listing","job"]}).notNull(),entityId:text("entity_id").notNull(),createdAt:timestamp("created_at",{withTimezone:true}).notNull().$defaultFn(()=>new Date())},t=>[uniqueIndex("favorites_user_entity_uq").on(t.userId,t.entityType,t.entityId)]);
export const reports=pgTable("reports",{id:text("id").primaryKey(),reporterId:text("reporter_id").notNull().references(()=>profiles.id),entityType:text("entity_type").notNull(),entityId:text("entity_id").notNull(),reason:text("reason").notNull(),details:text("details"),status:text("status",{enum:["open","reviewing","resolved","dismissed"]}).notNull().default("open"),resolvedBy:text("resolved_by").references(()=>profiles.id),resolvedAt:timestamp("resolved_at",{withTimezone:true}),...time},t=>[index("reports_status_created_idx").on(t.status,t.createdAt)]);
export const systemSettings=pgTable("system_settings",{key:text("key").primaryKey(),value:text("value").notNull(),valueType:text("value_type",{enum:["string","number","boolean","json"]}).notNull(),public:boolean("public").notNull().default(false),updatedBy:text("updated_by").references(()=>profiles.id),updatedAt:timestamp("updated_at",{withTimezone:true}).notNull().$defaultFn(()=>new Date())});
export const featureFlags=pgTable("feature_flags",{key:text("key").primaryKey(),nameAr:text("name_ar").notNull(),enabled:boolean("enabled").notNull().default(false),description:text("description"),updatedBy:text("updated_by").references(()=>profiles.id),updatedAt:timestamp("updated_at",{withTimezone:true}).notNull().$defaultFn(()=>new Date())});

export const communityPosts=pgTable("community_posts",{id:text("id").primaryKey(),authorId:text("author_id").notNull().references(()=>profiles.id,{onDelete:"cascade"}),body:text("body").notNull(),locationId:text("location_id").references(()=>locations.id),status:text("status",{enum:["published","hidden","reported"]}).notNull().default("published"),...time},t=>[index("community_posts_status_created_idx").on(t.status,t.createdAt),index("community_posts_author_idx").on(t.authorId)]);
export const communityComments=pgTable("community_comments",{id:text("id").primaryKey(),postId:text("post_id").notNull().references(()=>communityPosts.id,{onDelete:"cascade"}),authorId:text("author_id").notNull().references(()=>profiles.id,{onDelete:"cascade"}),body:text("body").notNull(),status:text("status",{enum:["published","hidden","reported"]}).notNull().default("published"),...time},t=>[index("community_comments_post_created_idx").on(t.postId,t.createdAt)]);
export const communityLikes=pgTable("community_likes",{id:text("id").primaryKey(),postId:text("post_id").notNull().references(()=>communityPosts.id,{onDelete:"cascade"}),userId:text("user_id").notNull().references(()=>profiles.id,{onDelete:"cascade"}),createdAt:timestamp("created_at",{withTimezone:true}).notNull().$defaultFn(()=>new Date())},t=>[uniqueIndex("community_likes_post_user_uq").on(t.postId,t.userId)]);

export const questions=pgTable("questions",{id:text("id").primaryKey(),authorId:text("author_id").notNull().references(()=>profiles.id,{onDelete:"cascade"}),title:text("title").notNull(),body:text("body").notNull(),categoryId:text("category_id").references(()=>categories.id),status:text("status",{enum:["open","answered","closed","hidden"]}).notNull().default("open"),...time},t=>[index("questions_status_created_idx").on(t.status,t.createdAt),index("questions_author_idx").on(t.authorId)]);
export const answers=pgTable("answers",{id:text("id").primaryKey(),questionId:text("question_id").notNull().references(()=>questions.id,{onDelete:"cascade"}),authorId:text("author_id").notNull().references(()=>profiles.id,{onDelete:"cascade"}),body:text("body").notNull(),isAccepted:boolean("is_accepted").notNull().default(false),status:text("status",{enum:["published","hidden","reported"]}).notNull().default("published"),...time},t=>[index("answers_question_created_idx").on(t.questionId,t.createdAt)]);
export const questionVotes=pgTable("question_votes",{id:text("id").primaryKey(),questionId:text("question_id").notNull().references(()=>questions.id,{onDelete:"cascade"}),userId:text("user_id").notNull().references(()=>profiles.id,{onDelete:"cascade"}),value:integer("value").notNull().default(1),createdAt:timestamp("created_at",{withTimezone:true}).notNull().$defaultFn(()=>new Date())},t=>[uniqueIndex("question_votes_question_user_uq").on(t.questionId,t.userId)]);

export const listings=pgTable("listings",{id:text("id").primaryKey(),ownerId:text("owner_id").notNull().references(()=>profiles.id,{onDelete:"cascade"}),kind:text("kind",{enum:["classified","car","property","job"]}).notNull(),categoryId:text("category_id").references(()=>categories.id),locationId:text("location_id").references(()=>locations.id),title:text("title").notNull(),description:text("description").notNull(),price:doublePrecision("price"),phone:text("phone").notNull(),attributesJson:text("attributes_json").notNull().default("{}"),status:text("status",{enum:["pending","active","sold","expired","rejected","suspended"]}).notNull().default("pending"),featured:boolean("featured").notNull().default(false),expiresAt:timestamp("expires_at",{withTimezone:true}),...time},t=>[index("listings_kind_status_created_idx").on(t.kind,t.status,t.createdAt),index("listings_owner_idx").on(t.ownerId)]);
export const jobApplications=pgTable("job_applications",{id:text("id").primaryKey(),listingId:text("listing_id").notNull().references(()=>listings.id,{onDelete:"cascade"}),applicantId:text("applicant_id").notNull().references(()=>profiles.id,{onDelete:"cascade"}),coverNote:text("cover_note").notNull(),status:text("status",{enum:["submitted","reviewing","accepted","rejected","withdrawn"]}).notNull().default("submitted"),...time},t=>[uniqueIndex("job_applications_listing_applicant_uq").on(t.listingId,t.applicantId)]);

export const conversations=pgTable("conversations",{id:text("id").primaryKey(),subject:text("subject"),entityType:text("entity_type"),entityId:text("entity_id"),createdBy:text("created_by").notNull().references(()=>profiles.id),...time},t=>[index("conversations_entity_idx").on(t.entityType,t.entityId)]);
export const conversationMembers=pgTable("conversation_members",{id:text("id").primaryKey(),conversationId:text("conversation_id").notNull().references(()=>conversations.id,{onDelete:"cascade"}),userId:text("user_id").notNull().references(()=>profiles.id,{onDelete:"cascade"}),lastReadAt:timestamp("last_read_at",{withTimezone:true}),createdAt:timestamp("created_at",{withTimezone:true}).notNull().$defaultFn(()=>new Date())},t=>[uniqueIndex("conversation_members_conversation_user_uq").on(t.conversationId,t.userId),index("conversation_members_user_idx").on(t.userId)]);
export const messages=pgTable("messages",{id:text("id").primaryKey(),conversationId:text("conversation_id").notNull().references(()=>conversations.id,{onDelete:"cascade"}),senderId:text("sender_id").notNull().references(()=>profiles.id),body:text("body").notNull(),createdAt:timestamp("created_at",{withTimezone:true}).notNull().$defaultFn(()=>new Date()),deletedAt:timestamp("deleted_at",{withTimezone:true})},t=>[index("messages_conversation_created_idx").on(t.conversationId,t.createdAt)]);

export const authCredentials=pgTable("auth_credentials",{id:text("id").primaryKey(),userId:text("user_id").notNull().references(()=>profiles.id,{onDelete:"cascade"}),passwordHash:text("password_hash").notNull(),passwordSalt:text("password_salt").notNull(),iterations:integer("iterations").notNull().default(310000),createdAt:timestamp("created_at",{withTimezone:true}).notNull().$defaultFn(()=>new Date()),updatedAt:timestamp("updated_at",{withTimezone:true}).notNull().$defaultFn(()=>new Date())},t=>[uniqueIndex("auth_credentials_user_uq").on(t.userId)]);
export const authSessions=pgTable("auth_sessions",{id:text("id").primaryKey(),userId:text("user_id").notNull().references(()=>profiles.id,{onDelete:"cascade"}),tokenHash:text("token_hash").notNull(),userAgent:text("user_agent"),ipHash:text("ip_hash"),expiresAt:timestamp("expires_at",{withTimezone:true}).notNull(),revokedAt:timestamp("revoked_at",{withTimezone:true}),createdAt:timestamp("created_at",{withTimezone:true}).notNull().$defaultFn(()=>new Date())},t=>[uniqueIndex("auth_sessions_token_uq").on(t.tokenHash),index("auth_sessions_user_expiry_idx").on(t.userId,t.expiresAt)]);
export const passwordResetTokens=pgTable("password_reset_tokens",{id:text("id").primaryKey(),userId:text("user_id").notNull().references(()=>profiles.id,{onDelete:"cascade"}),tokenHash:text("token_hash").notNull(),expiresAt:timestamp("expires_at",{withTimezone:true}).notNull(),usedAt:timestamp("used_at",{withTimezone:true}),createdAt:timestamp("created_at",{withTimezone:true}).notNull().$defaultFn(()=>new Date())},t=>[uniqueIndex("password_reset_tokens_hash_uq").on(t.tokenHash),index("password_reset_tokens_user_idx").on(t.userId)]);

export const advertisements=pgTable("advertisements",{id:text("id").primaryKey(),ownerId:text("owner_id").notNull().references(()=>profiles.id),storeId:text("store_id").references(()=>stores.id,{onDelete:"cascade"}),placement:text("placement",{enum:["homepage_banner","category_banner","featured_store","featured_product","featured_classified","sponsored_content"]}).notNull(),entityType:text("entity_type").notNull(),entityId:text("entity_id").notNull(),title:text("title").notNull(),imageKey:text("image_key"),targetUrl:text("target_url"),status:text("status",{enum:["draft","pending","approved","rejected","active","expired"]}).notNull().default("draft"),startsAt:timestamp("starts_at",{withTimezone:true}).notNull(),endsAt:timestamp("ends_at",{withTimezone:true}).notNull(),approvedBy:text("approved_by").references(()=>profiles.id),...time},t=>[index("advertisements_placement_status_dates_idx").on(t.placement,t.status,t.startsAt,t.endsAt),index("advertisements_owner_idx").on(t.ownerId),check("advertisements_dates_check",sql`${t.endsAt}>${t.startsAt}`)]);
export const adEvents=pgTable("ad_events",{id:text("id").primaryKey(),adId:text("ad_id").notNull().references(()=>advertisements.id,{onDelete:"cascade"}),userId:text("user_id").references(()=>profiles.id),type:text("type",{enum:["impression","click"]}).notNull(),sessionKey:text("session_key"),createdAt:timestamp("created_at",{withTimezone:true}).notNull().$defaultFn(()=>new Date())},t=>[index("ad_events_ad_type_created_idx").on(t.adId,t.type,t.createdAt)]);
export const paymentTransactions=pgTable("payment_transactions",{id:text("id").primaryKey(),subscriptionId:text("subscription_id").references(()=>subscriptions.id),provider:text("provider").notNull(),providerReference:text("provider_reference"),amount:doublePrecision("amount").notNull(),currency:text("currency").notNull().default("EGP"),status:text("status",{enum:["created","pending","paid","failed","refunded"]}).notNull().default("created"),metadataJson:text("metadata_json").notNull().default("{}"),...time},t=>[uniqueIndex("payment_transactions_provider_ref_uq").on(t.provider,t.providerReference),check("payment_transactions_amount_check",sql`${t.amount}>=0`)]);
export const driverProfiles=pgTable("driver_profiles",{id:text("id").primaryKey(),userId:text("user_id").notNull().references(()=>profiles.id,{onDelete:"cascade"}),phone:text("phone").notNull(),vehicleType:text("vehicle_type").notNull(),vehiclePlate:text("vehicle_plate"),available:boolean("available").notNull().default(false),status:text("status",{enum:["pending","active","suspended","rejected"]}).notNull().default("pending"),...time},t=>[uniqueIndex("driver_profiles_user_uq").on(t.userId),index("driver_profiles_available_status_idx").on(t.available,t.status)]);
export const deliveries=pgTable("deliveries",{id:text("id").primaryKey(),orderId:text("order_id").notNull().references(()=>orders.id),driverId:text("driver_id").notNull().references(()=>driverProfiles.id),assignedBy:text("assigned_by").notNull().references(()=>profiles.id),status:text("status",{enum:["assigned","accepted","picked_up","out_for_delivery","delivered","cancelled"]}).notNull().default("assigned"),acceptedAt:timestamp("accepted_at",{withTimezone:true}),pickedUpAt:timestamp("picked_up_at",{withTimezone:true}),deliveredAt:timestamp("delivered_at",{withTimezone:true}),...time},t=>[uniqueIndex("deliveries_order_uq").on(t.orderId),index("deliveries_driver_status_idx").on(t.driverId,t.status)]);
export const analyticsEvents=pgTable("analytics_events",{id:text("id").primaryKey(),userId:text("user_id").references(()=>profiles.id),sessionKey:text("session_key"),event:text("event").notNull(),entityType:text("entity_type"),entityId:text("entity_id"),metadataJson:text("metadata_json").notNull().default("{}"),createdAt:timestamp("created_at",{withTimezone:true}).notNull().$defaultFn(()=>new Date())},t=>[index("analytics_event_created_idx").on(t.event,t.createdAt),index("analytics_entity_created_idx").on(t.entityType,t.entityId,t.createdAt)]);
export const supportTickets=pgTable("support_tickets",{id:text("id").primaryKey(),requesterId:text("requester_id").notNull().references(()=>profiles.id),assignedAdminId:text("assigned_admin_id").references(()=>profiles.id),subject:text("subject").notNull(),priority:text("priority",{enum:["low","normal","high","urgent"]}).notNull().default("normal"),status:text("status",{enum:["open","pending","closed"]}).notNull().default("open"),closedAt:timestamp("closed_at",{withTimezone:true}),...time},t=>[index("support_tickets_requester_status_idx").on(t.requesterId,t.status),index("support_tickets_assignee_status_idx").on(t.assignedAdminId,t.status)]);
export const supportMessages=pgTable("support_messages",{id:text("id").primaryKey(),ticketId:text("ticket_id").notNull().references(()=>supportTickets.id,{onDelete:"cascade"}),senderId:text("sender_id").notNull().references(()=>profiles.id),body:text("body").notNull(),createdAt:timestamp("created_at",{withTimezone:true}).notNull().$defaultFn(()=>new Date())},t=>[index("support_messages_ticket_created_idx").on(t.ticketId,t.createdAt)]);
export const recentSearches=pgTable("recent_searches",{id:text("id").primaryKey(),userId:text("user_id").notNull().references(()=>profiles.id,{onDelete:"cascade"}),query:text("query").notNull(),filtersJson:text("filters_json").notNull().default("{}"),createdAt:timestamp("created_at",{withTimezone:true}).notNull().$defaultFn(()=>new Date())},t=>[index("recent_searches_user_created_idx").on(t.userId,t.createdAt)]);
