import { and, desc, eq, isNull, sql } from "drizzle-orm";
import { getDb } from "../../../db";
import { answers, profiles, questionVotes, questions, reports } from "../../../db/pg-schema";
import { requireApiUser } from "../../lib/authz";

export async function GET(request:Request){
  const db=getDb(),questionId=new URL(request.url).searchParams.get("questionId");
  if(questionId){
    const [question]=await db.select({id:questions.id,title:questions.title,body:questions.body,status:questions.status,createdAt:questions.createdAt,authorId:questions.authorId,author:profiles.fullName,votes:sql<number>`coalesce(sum(${questionVotes.value}),0)`}).from(questions).innerJoin(profiles,eq(profiles.id,questions.authorId)).leftJoin(questionVotes,eq(questionVotes.questionId,questions.id)).where(and(eq(questions.id,questionId),isNull(questions.deletedAt),sql`${questions.status} != 'hidden'`)).groupBy(questions.id,profiles.fullName).limit(1);
    if(!question)return Response.json({error:"السؤال غير موجود"},{status:404});
    const answerRows=await db.select({id:answers.id,body:answers.body,isAccepted:answers.isAccepted,createdAt:answers.createdAt,authorId:answers.authorId,author:profiles.fullName}).from(answers).innerJoin(profiles,eq(profiles.id,answers.authorId)).where(and(eq(answers.questionId,questionId),eq(answers.status,"published"),isNull(answers.deletedAt))).orderBy(desc(answers.isAccepted),answers.createdAt);
    return Response.json({question,answers:answerRows});
  }
  const rows=await db.select({id:questions.id,title:questions.title,body:questions.body,status:questions.status,createdAt:questions.createdAt,author:profiles.fullName,answerCount:sql<number>`count(distinct ${answers.id})`,votes:sql<number>`coalesce(sum(distinct ${questionVotes.value}),0)`}).from(questions).innerJoin(profiles,eq(profiles.id,questions.authorId)).leftJoin(answers,and(eq(answers.questionId,questions.id),eq(answers.status,"published"))).leftJoin(questionVotes,eq(questionVotes.questionId,questions.id)).where(and(isNull(questions.deletedAt),sql`${questions.status} != 'hidden'`)).groupBy(questions.id,profiles.fullName).orderBy(desc(questions.createdAt)).limit(100);
  return Response.json({questions:rows});
}

export async function POST(request:Request){try{const user=await requireApiUser(),body=await request.json() as {title?:string;body?:string},title=body.title?.trim()??"",details=body.body?.trim()??"";if(title.length<5||title.length>160||details.length<10||details.length>3000)return Response.json({error:"اكتب عنوانًا واضحًا وتفاصيل كافية"},{status:400});const db=getDb(),[question]=await db.insert(questions).values({id:crypto.randomUUID(),authorId:user.id,title,body:details}).returning();return Response.json({question},{status:201})}catch(e){if(e instanceof Response)return e;return Response.json({error:"تعذر إرسال السؤال"},{status:500})}}

export async function PUT(request:Request){try{const user=await requireApiUser(),body=await request.json() as {questionId?:string;body?:string},content=body.body?.trim()??"";if(!body.questionId||content.length<3||content.length>3000)return Response.json({error:"الإجابة غير صالحة"},{status:400});const db=getDb(),available=await db.select({id:questions.id}).from(questions).where(and(eq(questions.id,body.questionId),sql`${questions.status} in ('open','answered')`,isNull(questions.deletedAt))).limit(1);if(!available.length)return Response.json({error:"السؤال غير متاح للإجابة"},{status:404});const [answer]=await db.insert(answers).values({id:crypto.randomUUID(),questionId:body.questionId,authorId:user.id,body:content}).returning();return Response.json({answer},{status:201})}catch(e){if(e instanceof Response)return e;return Response.json({error:"تعذر إرسال الإجابة"},{status:500})}}

export async function PATCH(request:Request){try{const user=await requireApiUser(),body=await request.json() as {action?:"vote"|"accept"|"report";questionId?:string;answerId?:string;reason?:string},db=getDb();if(!body.questionId||!body.action)return Response.json({error:"بيانات الإجراء ناقصة"},{status:400});if(body.action==="vote"){await db.insert(questionVotes).values({id:crypto.randomUUID(),questionId:body.questionId,userId:user.id,value:1}).onConflictDoUpdate({target:[questionVotes.questionId,questionVotes.userId],set:{value:1}});return Response.json({ok:true})}if(body.action==="accept"){if(!body.answerId)return Response.json({error:"الإجابة مطلوبة"},{status:400});const [owned]=await db.select({id:questions.id}).from(questions).where(and(eq(questions.id,body.questionId),eq(questions.authorId,user.id),isNull(questions.deletedAt))).limit(1);if(!owned)return Response.json({error:"صاحب السؤال فقط يختار أفضل إجابة"},{status:403});await db.transaction(async tx=>{await tx.update(answers).set({isAccepted:false,updatedAt:new Date()}).where(eq(answers.questionId,body.questionId!));const accepted=await tx.update(answers).set({isAccepted:true,updatedAt:new Date()}).where(and(eq(answers.id,body.answerId!),eq(answers.questionId,body.questionId!))).returning({id:answers.id});if(!accepted.length)throw new Error("answer_not_found");await tx.update(questions).set({status:"answered",updatedAt:new Date()}).where(eq(questions.id,body.questionId!))});return Response.json({ok:true})}const reason=body.reason?.trim()||"محتوى غير مناسب";await db.insert(reports).values({id:crypto.randomUUID(),reporterId:user.id,entityType:"question",entityId:body.questionId,reason});return Response.json({ok:true},{status:201})}catch(e){if(e instanceof Response)return e;return Response.json({error:"تعذر تنفيذ الإجراء"},{status:500})}}

export async function DELETE(request:Request){try{const user=await requireApiUser(),questionId=new URL(request.url).searchParams.get("questionId");if(!questionId)return Response.json({error:"السؤال مطلوب"},{status:400});const rows=await getDb().update(questions).set({deletedAt:new Date(),updatedAt:new Date()}).where(and(eq(questions.id,questionId),eq(questions.authorId,user.id),isNull(questions.deletedAt))).returning({id:questions.id});return rows.length?Response.json({ok:true}):Response.json({error:"لا تملك حذف هذا السؤال"},{status:403})}catch(e){if(e instanceof Response)return e;return Response.json({error:"تعذر حذف السؤال"},{status:500})}}
