import postgres from "postgres";
if(!process.env.DATABASE_URL)throw new Error("DATABASE_URL is required");
const sql=postgres(process.env.DATABASE_URL,{max:1,prepare:false}),now=new Date();

await sql`insert into system_settings (key,value,value_type,public,updated_at) values ('merchant_monthly_price_egp','149','number',true,${now}),('merchant_trial_days','30','number',true,${now}) on conflict (key) do update set value=excluded.value,value_type=excluded.value_type,public=excluded.public,updated_at=excluded.updated_at`;
await sql`insert into subscription_plans (id,code,name_ar,price,duration_days,trial_days,features_json,active,created_at,updated_at) values ('plan-merchant-basic','merchant-basic','الخطة الأساسية',149,30,30,'["store","products","orders"]',true,${now},${now}) on conflict (code) do update set name_ar=excluded.name_ar,price=excluded.price,duration_days=excluded.duration_days,trial_days=excluded.trial_days,features_json=excluded.features_json,active=true,updated_at=excluded.updated_at`;

// Official administrative division of Dierb Nigm, Sharqia Governorate:
// https://www.sharkia.gov.eg/areas/dyarb/division.aspx?ID=1
const roots=[{id:"loc-sharkia",parentId:null,type:"governorate",name:"الشرقية",slug:"sharkia",sort:1},{id:"loc-dierb-center",parentId:"loc-sharkia",type:"center",name:"مركز ديرب نجم",slug:"dierb-nigm",sort:1},{id:"loc-dierb-city",parentId:"loc-dierb-center",type:"city",name:"مدينة ديرب نجم",slug:"dierb-nigm-city",sort:1}];
const villages=[["الصانية","elsania"],["برمكيم","barmakeem"],["جميزة بني عمرو","gameza-bani-amr"],["الصويني","elsoweiny"],["دبيج","debeeg"],["صافور","safoor"],["المنا صافور","el-mana-safoor"],["طحا المرج","taha-el-marj"],["ديرب السوق","dierb-el-souq"],["كفر أبو بري","kafr-abu-bari"],["الجواشنة","el-gawashna"],["الميساه","el-maysa"],["منشأة كشك","manshaet-keshk"],["منشية عودة سالم","manshiyet-awda-salem"],["قرموط صهبرة","qarmout-sahbara"],["حصة الرهبان","hesset-el-rohban"],["شبرا صورة","shubra-soura"],["كفر اللبا","kafr-el-labba"],["كفر العكل","kafr-el-akl"],["الهوابر","el-hawaber"],["أبو عيد","abu-eid"],["صهبرة","sahbara"],["منشأة صهبرة","manshaet-sahbara"],["أبو متنا","abu-matna"],["بهنيا","bahnaya"],["كراديس","karadees"],["صفط زريق","saft-zureiq"],["القطايع","el-qataie"],["المجفف","el-mogaffaf"],["إكوة","ekwa"],["كفر الباشا","kafr-el-basha"],["فرغان","farghan"],["شنبارة منقلا","shanbara-menqala"],["منشأة صفوت","manshaet-safwat"],["تل القاضي","tal-el-qadi"],["كفر الجندي","kafr-el-gendy"],["العصايد","el-asayed"],["المناحريت","el-manahreet"],["إكراش","ekrash"],["قاويشة","qawisha"],["العطارين","el-attareen"],["منشأة قاسم","manshaet-qasem"],["شوبك إكراش","shobak-ekrash"],["كفر الحاج حسن","kafr-el-hag-hassan"]];
for(const item of roots){await sql`insert into locations (id,parent_id,type,name_ar,slug,active,sort_order,created_at,updated_at) values (${item.id},${item.parentId},${item.type},${item.name},${item.slug},true,${item.sort},${now},${now}) on conflict (id) do update set parent_id=excluded.parent_id,type=excluded.type,name_ar=excluded.name_ar,slug=excluded.slug,active=true,sort_order=excluded.sort_order,updated_at=excluded.updated_at`}
for(let i=0;i<villages.length;i++){const [name,slug]=villages[i],id=`loc-dierb-v-${String(i+1).padStart(2,"0")}`;await sql`insert into locations (id,parent_id,type,name_ar,slug,active,sort_order,created_at,updated_at) values (${id},'loc-dierb-center','village',${name},${slug},true,${i+10},${now},${now}) on conflict (id) do update set parent_id=excluded.parent_id,type=excluded.type,name_ar=excluded.name_ar,slug=excluded.slug,active=true,sort_order=excluded.sort_order,updated_at=excluded.updated_at`}

const categories=[
 ["store","سوبر ماركت وبقالة","supermarkets","🛒"],["store","مطاعم ومأكولات","restaurants","🍽️"],["store","صيدليات","pharmacies","💊"],["store","مخابز وحلويات","bakeries","🥖"],["store","خضار وفاكهة","produce","🥬"],["store","جزارة ودواجن","butchers","🥩"],["store","ملابس","clothing","👕"],["store","أحذية وشنط","shoes-bags","👟"],["store","موبايلات وإكسسوارات","mobiles","📱"],["store","أجهزة وإلكترونيات","electronics","💻"],["store","أثاث ومفروشات","furniture","🛋️"],["store","أدوات منزلية","homeware","🏠"],["store","قطع غيار سيارات","auto-parts","🚗"],["store","مواد بناء وتشطيبات","building-materials","🧱"],["store","مكتبات وأدوات مدرسية","stationery","📚"],["store","هدايا وعطور","gifts-perfumes","🎁"],["store","تجميل وعناية شخصية","beauty","💄"],["store","كافيهات ومشروبات","cafes","☕"],["store","مستلزمات زراعية","agriculture","🌾"],["store","تجارة جملة","wholesale","📦"],
 ["service","أطباء وعيادات","doctors-clinics","🩺"],["service","معامل وتحاليل","labs","🧪"],["service","تمريض ورعاية منزلية","nursing","🏥"],["service","سباكة","plumbing","🔧"],["service","كهرباء","electricity","⚡"],["service","نجارة وأثاث","carpentry","🪚"],["service","نقاشة وتشطيبات","painting-finishing","🎨"],["service","صيانة أجهزة منزلية","appliance-repair","🧰"],["service","ميكانيكا وكهرباء سيارات","car-repair","🚘"],["service","محاماة","lawyers","⚖️"],["service","محاسبة وضرائب","accounting","🧾"],["service","مدرسون ودروس","tutors","🎓"],["service","نظافة وتعقيم","cleaning","🧹"],["service","نقل وشحن","transport","🚚"],["service","تصوير ومناسبات","photography","📷"],["service","كمبيوتر وشبكات","computer-service","🖥️"]
];
for(let i=0;i<categories.length;i++){const [entityType,name,slug,icon]=categories[i],id=`cat-${entityType}-${slug}`;await sql`insert into categories (id,parent_id,name_ar,slug,icon,entity_type,active,sort_order,created_at,updated_at) values (${id},null,${name},${slug},${icon},${entityType},true,${i+1},${now},${now}) on conflict (id) do update set name_ar=excluded.name_ar,slug=excluded.slug,icon=excluded.icon,entity_type=excluded.entity_type,active=true,sort_order=excluded.sort_order,updated_at=excluded.updated_at`}

await sql.end();
console.log(`System settings, merchant plan, ${villages.length} official Dierb Nigm villages, and ${categories.length} directory categories are ready.`);
