"use client";
import { FormEvent,useCallback,useEffect,useState } from "react";
type Question={id:string;title:string;body:string;author:string|null;status:string;answerCount:number;votes:number;createdAt:string};
type Answer={id:string;body:string;author:string|null;isAccepted:boolean;createdAt:string};
export function AskBoard(){
  const [rows,setRows]=useState<Question[]>([]),[selected,setSelected]=useState<Question|null>(null),[answerRows,setAnswerRows]=useState<Answer[]>([]),[title,setTitle]=useState(""),[body,setBody]=useState(""),[answer,setAnswer]=useState(""),[message,setMessage]=useState("");
  const load=useCallback(async()=>{const r=await fetch("/api/questions");if(r.ok)setRows((await r.json()).questions)},[]);
  useEffect(()=>{void load()},[load]);
  async function open(q:Question){const r=await fetch(`/api/questions?questionId=${encodeURIComponent(q.id)}`),data=await r.json();if(r.ok){setSelected(data.question);setAnswerRows(data.answers)}else setMessage(data.error)}
  async function submit(e:FormEvent){e.preventDefault();const r=await fetch("/api/questions",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({title,body})}),data=await r.json();setMessage(r.ok?"تم إرسال السؤال":data.error);if(r.ok){setTitle("");setBody("");await load()}}
  async function sendAnswer(e:FormEvent){e.preventDefault();if(!selected)return;const r=await fetch("/api/questions",{method:"PUT",headers:{"content-type":"application/json"},body:JSON.stringify({questionId:selected.id,body:answer})}),data=await r.json();setMessage(r.ok?"تم نشر الإجابة":data.error);if(r.ok){setAnswer("");await open(selected);await load()}}
  async function action(action:"vote"|"accept"|"report",answerId?:string){if(!selected)return;const r=await fetch("/api/questions",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({action,questionId:selected.id,answerId})}),data=await r.json();setMessage(r.ok?action==="vote"?"تم تسجيل صوتك":action==="accept"?"تم اختيار أفضل إجابة":"تم إرسال البلاغ":data.error);if(r.ok){await open(selected);await load()}}
  return <div className="content-split"><div className="social-compose"><h2>اسأل سؤالك</h2><form onSubmit={submit}><input required minLength={5} maxLength={160} value={title} onChange={e=>setTitle(e.target.value)} placeholder="عنوان السؤال"/><textarea required minLength={10} maxLength={3000} value={body} onChange={e=>setBody(e.target.value)} placeholder="وضّح التفاصيل علشان الناس تساعدك"/><button className="primary">إرسال السؤال</button></form>{message&&<p>{message}</p>}</div><div className="question-list">{rows.length===0?<div className="empty"><span>❓</span><h3>لا توجد أسئلة بعد</h3></div>:rows.map(q=><article key={q.id}><small>{q.status==="answered"?"تمت الإجابة":"مفتوح"} · {q.author||"عضو"}</small><h2>{q.title}</h2><p>{q.body}</p><b>{q.answerCount} إجابة · {q.votes||0} تصويت</b><button className="text-button" onClick={()=>open(q)}>فتح السؤال والإجابات</button></article>)}</div>{selected&&<section className="social-compose"><button className="text-button" onClick={()=>setSelected(null)}>إغلاق</button><h2>{selected.title}</h2><p>{selected.body}</p><div><button onClick={()=>action("vote")}>صوّت للسؤال</button><button onClick={()=>action("report")}>إبلاغ</button></div><form onSubmit={sendAnswer}><textarea required minLength={3} maxLength={3000} value={answer} onChange={e=>setAnswer(e.target.value)} placeholder="اكتب إجابتك"/><button className="primary">نشر الإجابة</button></form>{answerRows.map(a=><article key={a.id}><small>{a.author||"عضو"}{a.isAccepted?" · أفضل إجابة ✓":""}</small><p>{a.body}</p>{!a.isAccepted&&<button onClick={()=>action("accept",a.id)}>اختيار كأفضل إجابة</button>}</article>)}</section>}</div>}
