"use client";
import { FormEvent,useMemo,useState } from "react";
import { StoreSetup } from "./store-setup";
type Store={id:string;name:string;status:string;phone:string;address:string;createdAt:string;updatedAt:string;deletedAt:string|null;[key:string]:unknown};
type Product={id:string;storeId:string;name:string;price:number;stock:number;unit:string;active:boolean;createdAt:string;updatedAt:string;deletedAt:string|null;[key:string]:unknown};
type Order={id:string;orderNumber:string;storeId:string;status:string;total:number;createdAt:string;updatedAt:string;deletedAt:string|null;[key:string]:unknown};
type Sub={id:string;storeId:string;status:string;endsAt:string;planName:string};
type Coupon={id:string;storeId:string;code:string;discountType:string;discountValue:number;minimumOrder:number;startsAt:string;endsAt:string;active:boolean};
type Ad={id:string;storeId:string|null;title:string;placement:string;status:string;startsAt:string;endsAt:string};
export function MerchantDashboard({initialStores,initialProducts,initialOrders,subscriptions,coupons,ads}:{initialStores:Store[];initialProducts:Product[];initialOrders:Order[];subscriptions:Sub[];coupons:Coupon[];ads:Ad[]}){
 const [products,setProducts]=useState(initialProducts),[orderRows,setOrderRows]=useState(initialOrders),[couponRows,setCouponRows]=useState(coupons),[adRows,setAdRows]=useState(ads),[busy,setBusy]=useState(""),[message,setMessage]=useState("");
 const revenue=useMemo(()=>orderRows.filter(o=>o.status==="delivered").reduce((n,o)=>n+o.total,0),[orderRows]);
 async function addProduct(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy("product");setMessage("");const form=e.currentTarget,payload=Object.fromEntries(new FormData(form));try{const res=await fetch("/api/products",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(payload)});const data=await res.json() as {product?:Product;error?:string};if(!res.ok||!data.product)throw new Error(data.error||"تعذر إضافة المنتج");setProducts(x=>[data.product!,...x]);setMessage("تمت إضافة المنتج وحفظ المخزون.");form.reset()}catch(e){setMessage(e instanceof Error?e.message:"حدث خطأ")}finally{setBusy("")}}
 async function editProduct(p:Product,field:"price"|"stock"){const raw=window.prompt(field==="price"?"اكتب السعر الجديد":"اكتب المخزون الجديد",String(p[field]));if(raw===null)return;setBusy(p.id);const value=Number(raw);const r=await fetch("/api/products",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({id:p.id,[field]:value})}),data=await r.json();if(r.ok&&data.product){setProducts(x=>x.map(y=>y.id===p.id?{...y,...data.product}:y));setMessage("تم تحديث المنتج.")}else setMessage(data.error||"تعذر تعديل المنتج");setBusy("")}
 async function archiveProduct(p:Product){if(!window.confirm(`أرشفة ${p.name}؟ لن يظهر في السوق بعد ذلك.`))return;setBusy(p.id);const r=await fetch(`/api/products?id=${encodeURIComponent(p.id)}`,{method:"DELETE"}),data=await r.json();if(r.ok){setProducts(x=>x.filter(y=>y.id!==p.id));setMessage("تمت أرشفة المنتج.")}else setMessage(data.error||"تعذر أرشفة المنتج");setBusy("")}
 async function moveOrder(orderId:string,status:string){setBusy(orderId);setMessage("");try{const res=await fetch("/api/business/orders",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({orderId,status})});const data=await res.json() as {error?:string};if(!res.ok)throw new Error(data.error||"تعذر تحديث الطلب");setOrderRows(x=>x.map(o=>o.id===orderId?{...o,status}:o))}catch(e){setMessage(e instanceof Error?e.message:"حدث خطأ")}finally{setBusy("")}}
 async function addCoupon(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy("coupon");const form=e.currentTarget,p=Object.fromEntries(new FormData(form)),r=await fetch("/api/offers",{method:"PUT",headers:{"content-type":"application/json"},body:JSON.stringify(p)}),data=await r.json();if(r.ok&&data.coupon){setCouponRows(x=>[{...data.coupon,startsAt:new Date(data.coupon.startsAt).toISOString(),endsAt:new Date(data.coupon.endsAt).toISOString()},...x]);form.reset();setMessage("تم إنشاء الكوبون.")}else setMessage(data.error||"تعذر إنشاء الكوبون");setBusy("")}
 async function requestAd(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy("ad");const form=e.currentTarget,p=Object.fromEntries(new FormData(form));const payload={...p,entityType:"store",entityId:p.storeId,targetUrl:"/market"};const r=await fetch("/api/ads",{method:"PUT",headers:{"content-type":"application/json"},body:JSON.stringify(payload)}),data=await r.json();if(r.ok&&data.advertisement){setAdRows(x=>[{...data.advertisement,startsAt:new Date(data.advertisement.startsAt).toISOString(),endsAt:new Date(data.advertisement.endsAt).toISOString()},...x]);form.reset();setMessage("تم إرسال طلب الإعلان للمراجعة.")}else setMessage(data.error||"تعذر إرسال الإعلان");setBusy("")}
 const next:Record<string,{label:string;value:string}|undefined>={pending:{label:"تأكيد",value:"confirmed"},confirmed:{label:"بدء التجهيز",value:"preparing"},preparing:{label:"جاهز",value:"ready"},ready:{label:"تم التسليم",value:"delivered"}};
 if(!initialStores.length)return <StoreSetup/>;
 return <><div className="dash-kpis"><article><span>المتاجر</span><b>{initialStores.length}</b><small>{initialStores.filter(s=>s.status==="active").length} نشط</small></article><article><span>المنتجات النشطة</span><b>{products.filter(p=>p.active).length}</b><small>إدارة ومخزون</small></article><article><span>الطلبات الجديدة</span><b>{orderRows.filter(o=>o.status==="pending").length}</b><small>تحتاج متابعة</small></article><article><span>إيراد الطلبات المسلّمة</span><b>{revenue.toLocaleString("ar-EG")} ج</b><small>إجمالي حقيقي</small></article><article><span>الكوبونات</span><b>{couponRows.filter(c=>c.active).length}</b><small>نشطة</small></article><article><span>طلبات الإعلان</span><b>{adRows.filter(a=>a.status==="pending").length}</b><small>تنتظر المراجعة</small></article></div>
 {message&&<p className="form-message ok">{message}</p>}
 <section className="form-card" id="products"><div><span className="kicker">إدارة المخزون</span><h2>المنتجات</h2><p>أضف المنتج وعدّل السعر والمخزون أو أرشفه. كل عملية محمية بملكية المتجر على الخادم.</p></div><form onSubmit={addProduct}><label>المتجر<select name="storeId" required>{initialStores.map(s=><option value={s.id} key={s.id}>{s.name}</option>)}</select></label><label>اسم المنتج<input name="name" minLength={2} required/></label><label>السعر<input name="price" type="number" min="0" step="0.01" required/></label><label>المخزون<input name="stock" type="number" min="0" step="1" required/></label><label>الوحدة<select name="unit"><option>قطعة</option><option>كرتونة</option><option>كيلو</option><option>لتر</option></select></label><button className="primary" disabled={busy==="product"}>{busy==="product"?"جارٍ الحفظ...":"إضافة المنتج"}</button></form><div className="data-table">{products.length===0?<p>لم تتم إضافة منتجات بعد.</p>:products.map(p=><article key={p.id}><div><b>{p.name}</b><small>{p.stock} {p.unit} في المخزون</small></div><strong>{p.price.toLocaleString("ar-EG")} ج</strong><div><button disabled={busy===p.id} onClick={()=>editProduct(p,"price")}>السعر</button><button disabled={busy===p.id} onClick={()=>editProduct(p,"stock")}>المخزون</button><button className="reject" disabled={busy===p.id} onClick={()=>archiveProduct(p)}>أرشفة</button></div></article>)}</div></section>
 <section className="form-card" id="orders"><div><span className="kicker">دورة الطلب</span><h2>الطلبات</h2></div><div className="data-table">{orderRows.length===0?<p>لا توجد طلبات حتى الآن.</p>:orderRows.map(o=><article key={o.id}><div><b>{o.orderNumber}</b><small>{new Date(o.createdAt).toLocaleDateString("ar-EG")} • {o.status}</small></div><strong>{o.total.toLocaleString("ar-EG")} ج</strong>{next[o.status]&&<button className="approve" disabled={busy===o.id} onClick={()=>moveOrder(o.id,next[o.status]!.value)}>{next[o.status]!.label}</button>}</article>)}</div></section>
 <section className="form-card" id="coupons"><div><span className="kicker">التسويق</span><h2>الكوبونات</h2></div><form onSubmit={addCoupon}><label>المتجر<select name="storeId" required>{initialStores.map(s=><option value={s.id} key={s.id}>{s.name}</option>)}</select></label><label>الكود<input name="code" required minLength={3} placeholder="DERB10"/></label><label>نوع الخصم<select name="discountType"><option value="percentage">نسبة مئوية</option><option value="fixed">قيمة ثابتة</option></select></label><label>قيمة الخصم<input name="discountValue" type="number" min="1" step="0.01" required/></label><label>الحد الأدنى للطلب<input name="minimumOrder" type="number" min="0" defaultValue="0"/></label><label>الحد لكل مستخدم<input name="perUserLimit" type="number" min="1" defaultValue="1"/></label><label>يبدأ<input name="startsAt" type="datetime-local" required/></label><label>ينتهي<input name="endsAt" type="datetime-local" required/></label><button className="primary" disabled={busy==="coupon"}>إنشاء كوبون</button></form><div className="data-table">{couponRows.map(c=><article key={c.id}><div><b>{c.code}</b><small>{c.discountType==="percentage"?`${c.discountValue}%`:`${c.discountValue} ج`} · حد أدنى {c.minimumOrder} ج</small></div><span>{c.active?"نشط":"متوقف"}</span></article>)}</div></section>
 <section className="form-card" id="ads"><div><span className="kicker">ظهور مدفوع</span><h2>طلبات الإعلان</h2><p>لا يوجد نجاح وهمي: الطلب يظل Pending حتى اعتماد الإدارة.</p></div><form onSubmit={requestAd}><label>المتجر<select name="storeId" required>{initialStores.map(s=><option value={s.id} key={s.id}>{s.name}</option>)}</select></label><label>عنوان الحملة<input name="title" required minLength={3}/></label><label>المكان<select name="placement"><option value="homepage_banner">بانر الرئيسية</option><option value="featured_store">متجر مميز</option><option value="sponsored_content">محتوى ممول</option></select></label><label>يبدأ<input name="startsAt" type="datetime-local" required/></label><label>ينتهي<input name="endsAt" type="datetime-local" required/></label><button className="primary" disabled={busy==="ad"}>إرسال للمراجعة</button></form><div className="data-table">{adRows.map(a=><article key={a.id}><div><b>{a.title}</b><small>{a.placement}</small></div><span>{a.status}</span></article>)}</div></section>
 <section className="form-card" id="subscription"><div><span className="kicker">الاشتراك</span><h2>حالة الخطة</h2></div>{subscriptions.length===0?<p>يبدأ الاشتراك التجريبي بعد اعتماد المتجر.</p>:subscriptions.map(s=><article className="subscription-row" key={s.id}><b>{s.planName}</b><span>{s.status}</span><small>حتى {new Date(s.endsAt).toLocaleDateString("ar-EG")}</small></article>)}</section></>;
}
