"use client";
import { FormEvent, useMemo, useState } from "react";
import { StoreSetup } from "./store-setup";
type Store={id:string;name:string;status:string;phone:string;address:string;createdAt:string;updatedAt:string;deletedAt:string|null;[key:string]:unknown};
type Product={id:string;storeId:string;name:string;price:number;stock:number;unit:string;active:boolean;createdAt:string;updatedAt:string;deletedAt:string|null;[key:string]:unknown};
type Order={id:string;orderNumber:string;storeId:string;status:string;total:number;createdAt:string;updatedAt:string;deletedAt:string|null;[key:string]:unknown};
type Sub={id:string;storeId:string;status:string;endsAt:string;planName:string};
export function MerchantDashboard({initialStores,initialProducts,initialOrders,subscriptions}:{initialStores:Store[];initialProducts:Product[];initialOrders:Order[];subscriptions:Sub[]}){
 const [products,setProducts]=useState(initialProducts),[orderRows,setOrderRows]=useState(initialOrders),[busy,setBusy]=useState(""),[message,setMessage]=useState("");
 const revenue=useMemo(()=>orderRows.filter(o=>o.status==="delivered").reduce((n,o)=>n+o.total,0),[orderRows]);
 async function addProduct(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy("product");setMessage("");const form=e.currentTarget,payload=Object.fromEntries(new FormData(form));try{const res=await fetch("/api/products",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(payload)});const data=await res.json() as {product?:Product;error?:string};if(!res.ok||!data.product)throw new Error(data.error||"تعذر إضافة المنتج");setProducts(x=>[data.product!,...x]);setMessage("تمت إضافة المنتج وحفظ المخزون.");form.reset()}catch(e){setMessage(e instanceof Error?e.message:"حدث خطأ")}finally{setBusy("")}}
 async function moveOrder(orderId:string,status:string){setBusy(orderId);setMessage("");try{const res=await fetch("/api/business/orders",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({orderId,status})});const data=await res.json() as {error?:string};if(!res.ok)throw new Error(data.error||"تعذر تحديث الطلب");setOrderRows(x=>x.map(o=>o.id===orderId?{...o,status}:o))}catch(e){setMessage(e instanceof Error?e.message:"حدث خطأ")}finally{setBusy("")}}
 const next:Record<string,{label:string;value:string}|undefined>={pending:{label:"تأكيد",value:"confirmed"},confirmed:{label:"بدء التجهيز",value:"preparing"},preparing:{label:"جاهز",value:"ready"},ready:{label:"تم التسليم",value:"delivered"}};
 if(!initialStores.length)return <StoreSetup/>;
 return <><div className="dash-kpis"><article><span>المتاجر</span><b>{initialStores.length}</b><small>{initialStores.filter(s=>s.status==="active").length} نشط</small></article><article><span>الطلبات الجديدة</span><b>{orderRows.filter(o=>o.status==="pending").length}</b><small>من قاعدة البيانات</small></article><article><span>إيراد الطلبات المسلّمة</span><b>{revenue.toLocaleString("ar-EG")} ج</b><small>إجمالي حقيقي</small></article></div>
 {message&&<p className="form-message ok">{message}</p>}
 <section className="form-card" id="products"><div><span className="kicker">إدارة المخزون</span><h2>إضافة منتج</h2><p>المنتج مرتبط بمتجرك ولا يمكن لتاجر آخر تعديله.</p></div><form onSubmit={addProduct}><label>المتجر<select name="storeId" required>{initialStores.map(s=><option value={s.id} key={s.id}>{s.name}</option>)}</select></label><label>اسم المنتج<input name="name" minLength={2} required/></label><label>السعر<input name="price" type="number" min="0" step="0.01" required/></label><label>المخزون<input name="stock" type="number" min="0" step="1" required/></label><label>الوحدة<select name="unit"><option>قطعة</option><option>كرتونة</option><option>كيلو</option><option>لتر</option></select></label><button className="primary" disabled={busy==="product"}>{busy==="product"?"جارٍ الحفظ...":"إضافة المنتج"}</button></form><div className="data-table">{products.length===0?<p>لم تتم إضافة منتجات بعد.</p>:products.map(p=><article key={p.id}><div><b>{p.name}</b><small>{p.stock} {p.unit} في المخزون</small></div><strong>{p.price.toLocaleString("ar-EG")} ج</strong></article>)}</div></section>
 <section className="form-card" id="orders"><div><span className="kicker">دورة الطلب</span><h2>الطلبات</h2></div><div className="data-table">{orderRows.length===0?<p>لا توجد طلبات حتى الآن.</p>:orderRows.map(o=><article key={o.id}><div><b>{o.orderNumber}</b><small>{new Date(o.createdAt).toLocaleDateString("ar-EG")} • {o.status}</small></div><strong>{o.total.toLocaleString("ar-EG")} ج</strong>{next[o.status]&&<button className="approve" disabled={busy===o.id} onClick={()=>moveOrder(o.id,next[o.status]!.value)}>{next[o.status]!.label}</button>}</article>)}</div></section>
 <section className="form-card" id="subscription"><div><span className="kicker">الاشتراك</span><h2>حالة الخطة</h2></div>{subscriptions.length===0?<p>يبدأ الاشتراك التجريبي بعد اعتماد المتجر.</p>:subscriptions.map(s=><article className="subscription-row" key={s.id}><b>{s.planName}</b><span>{s.status}</span><small>حتى {new Date(s.endsAt).toLocaleDateString("ar-EG")}</small></article>)}</section></>;
}
