"use client";
import { useMemo,useState } from "react";
type Provider={id:string;name:string;profession:string;status:string;verified:boolean};
type RequestRow={id:string;providerId:string;customerName:string|null;details:string;preferredAt:string|null;status:string;createdAt:string};
const next:Record<string,Array<{label:string;value:string;kind?:"reject"}>>={pending:[{label:"قبول",value:"accepted"},{label:"رفض",value:"rejected",kind:"reject"}],accepted:[{label:"بدء التنفيذ",value:"in_progress"},{label:"إلغاء",value:"cancelled",kind:"reject"}],in_progress:[{label:"تم التنفيذ",value:"completed"},{label:"إلغاء",value:"cancelled",kind:"reject"}]};
const labels:Record<string,string>={pending:"جديد",accepted:"مقبول",in_progress:"جارٍ التنفيذ",completed:"مكتمل",rejected:"مرفوض",cancelled:"ملغي"};
export function ServiceProviderPanel({providers,initialRequests}:{providers:Provider[];initialRequests:RequestRow[]}){const [rows,setRows]=useState(initialRequests),[busy,setBusy]=useState(""),[message,setMessage]=useState("");const active=providers.filter(p=>p.status==="active").length,completed=useMemo(()=>rows.filter(r=>r.status==="completed").length,[rows]);async function move(id:string,status:string){setBusy(id+status);setMessage("");const r=await fetch("/api/services",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({requestId:id,status})}),data=await r.json();if(r.ok){setRows(x=>x.map(row=>row.id===id?{...row,status}:row));setMessage("تم تحديث حالة طلب الخدمة.")}else setMessage(data.error||"تعذر تحديث الطلب");setBusy("")}
 return <section id="service-business"><div className="form-card"><div><span className="kicker">ديرب للخدمات</span><h2>إدارة خدماتك</h2><p>ملفات الخدمة والطلبات مرتبطة بحسابك فقط.</p></div><div className="dash-kpis"><article><span>ملفات الخدمة</span><b>{providers.length}</b><small>{active} نشط</small></article><article><span>طلبات جديدة</span><b>{rows.filter(r=>r.status==="pending").length}</b><small>تحتاج رد</small></article><article><span>طلبات مكتملة</span><b>{completed}</b><small>إجمالي حقيقي</small></article></div><div className="data-table">{providers.map(p=><article key={p.id}><div><b>{p.name}</b><small>{p.profession}</small></div><span>{p.verified?"موثّق ✓":labels[p.status]||p.status}</span><a href={`/services/${p.id}`}>عرض الصفحة</a></article>)}</div></div>
 {message&&<p className="form-message ok">{message}</p>}
 <section className="form-card" id="service-requests"><div><span className="kicker">طلبات العملاء</span><h2>طلبات الخدمات</h2></div><div className="data-table">{rows.length===0?<p>لا توجد طلبات خدمة حتى الآن.</p>:rows.map(r=><article key={r.id}><div><b>{r.customerName||"عميل ديرب"}</b><small>{r.details}</small>{r.preferredAt&&<small>ميعاد مفضل: {new Date(r.preferredAt).toLocaleString("ar-EG")}</small>}<small>الحالة: {labels[r.status]||r.status}</small></div><div>{(next[r.status]||[]).map(a=><button key={a.value} className={a.kind==="reject"?"reject":"approve"} disabled={!!busy} onClick={()=>move(r.id,a.value)}>{a.label}</button>)}</div></article>)}</div></section></section>;
}
