"use client";
import { FormEvent,useEffect,useState } from "react";
type Option={id:string;name:string;type?:string;icon?:string|null};
export function StoreSetup(){
 const [busy,setBusy]=useState(false),[message,setMessage]=useState<{ok:boolean;text:string}|null>(null),[locations,setLocations]=useState<Option[]>([]),[categories,setCategories]=useState<Option[]>([]);
 useEffect(()=>{void fetch("/api/taxonomy?type=store").then(r=>r.ok?r.json():Promise.reject()).then(d=>{setLocations((d.locations as Option[]).filter(x=>x.type==="city"||x.type==="village"));setCategories(d.categories)}).catch(()=>setMessage({ok:false,text:"تعذر تحميل القرى والتصنيفات"}))},[]);
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setMessage(null);const form=new FormData(e.currentTarget);const payload=Object.fromEntries(form.entries());try{const res=await fetch("/api/stores",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(payload)});const data=await res.json() as {error?:string};if(!res.ok)throw new Error(data.error||"تعذر الحفظ");setMessage({ok:true,text:"تم حفظ المتجر وإرساله للمراجعة الحقيقية."});e.currentTarget.reset()}catch(err){setMessage({ok:false,text:err instanceof Error?err.message:"حدث خطأ"})}finally{setBusy(false)}}
 return <section className="form-card"><div><span className="kicker">الخطوة الأولى</span><h2>بيانات المتجر</h2><p>اختر القرية والتصنيف علشان نشاطك يظهر في دليل ديرب والبحث. لن يظهر للعامة إلا بعد مراجعة الإدارة.</p></div><form onSubmit={submit}><label>اسم النشاط<input name="name" minLength={3} required placeholder="مثال: ماركت البلد"/></label><label>التصنيف<select name="categoryId" required defaultValue=""><option value="" disabled>اختر نوع النشاط</option>{categories.map(x=><option value={x.id} key={x.id}>{x.icon?`${x.icon} `:""}{x.name}</option>)}</select></label><label>القرية/المدينة<select name="locationId" required defaultValue=""><option value="" disabled>اختر المكان</option>{locations.map(x=><option value={x.id} key={x.id}>{x.name}</option>)}</select></label><label>رقم الهاتف<input name="phone" inputMode="tel" minLength={8} required placeholder="01xxxxxxxxx"/></label><label>واتساب<input name="whatsapp" inputMode="tel" placeholder="اختياري"/></label><label className="full">العنوان بالتفصيل<input name="address" minLength={5} required placeholder="الشارع، علامة مميزة"/></label><label className="full">وصف النشاط<textarea name="description" rows={4} placeholder="اكتب نبذة واضحة عن نشاطك"/></label><button className="primary full" disabled={busy||!locations.length||!categories.length}>{busy?"جارٍ الحفظ...":"حفظ وإرسال للمراجعة"}</button>{message&&<p className={message.ok?"form-message ok":"form-message error"}>{message.text}</p>}</form></section>
}
