import Link from "next/link";
import { and,eq,isNull,sql } from "drizzle-orm";
import { notFound } from "next/navigation";
import { getDb } from "../../../db";
import { categories,locations,reviews,serviceProfiles } from "../../../db/pg-schema";
import { StartMessage } from "../../components/start-message";
import { ServiceRequestForm } from "./request-form";
export const dynamic="force-dynamic";
export default async function ServiceProviderPage({params}:{params:Promise<{id:string}>}){const {id}=await params,db=getDb();const [provider]=await db.select({id:serviceProfiles.id,ownerId:serviceProfiles.ownerId,name:serviceProfiles.name,profession:serviceProfiles.profession,description:serviceProfiles.description,phone:serviceProfiles.phone,whatsapp:serviceProfiles.whatsapp,priceFrom:serviceProfiles.priceFrom,availability:serviceProfiles.availability,verified:serviceProfiles.verified,locationName:locations.nameAr,categoryName:categories.nameAr,categoryIcon:categories.icon}).from(serviceProfiles).leftJoin(locations,eq(locations.id,serviceProfiles.locationId)).leftJoin(categories,eq(categories.id,serviceProfiles.categoryId)).where(and(eq(serviceProfiles.id,id),eq(serviceProfiles.status,"active"),isNull(serviceProfiles.deletedAt))).limit(1);if(!provider)notFound();const [rating]=await db.select({average:sql<number>`coalesce(avg(${reviews.rating}),0)`,count:sql<number>`count(*)`}).from(reviews).where(and(eq(reviews.entityType,"service"),eq(reviews.entityId,id),eq(reviews.status,"published")));return <main className="market-page"><header><Link className="brand" href="/"><span className="brand-mark">د</span><span><strong>ديرب</strong><small>الخدمات</small></span></Link><Link className="ghost" href="/services">كل الخدمات</Link></header><section className="service-profile-detail"><div className="service-avatar">{provider.categoryIcon||"🛠️"}</div><div><span className="kicker">{provider.categoryName||"خدمة محلية"}{provider.verified?" · موثّق ✓":""}</span><h1>{provider.name}</h1><h2>{provider.profession}</h2><p>{provider.description}</p><div className="product-rating">⭐ {Number(rating?.average??0).toFixed(1)} · {Number(rating?.count??0)} تقييم</div>{provider.locationName&&<p>📍 {provider.locationName}</p>}{provider.availability&&<p>🕒 {provider.availability}</p>}{provider.priceFrom!==null&&<strong>يبدأ من {provider.priceFrom.toLocaleString("ar-EG")} جنيه</strong>}<div className="contact-buttons"><a className="ghost" href={`tel:${provider.phone}`}>اتصال</a>{provider.whatsapp&&<a className="primary" href={`https://wa.me/2${provider.whatsapp.replace(/\D/g,"").replace(/^2/,"")}`} target="_blank" rel="noreferrer">واتساب</a>}<StartMessage recipientId={provider.ownerId} subject={`استفسار عن خدمة ${provider.name}`} returnTo={`/services/${provider.id}`}/></div></div></section><ServiceRequestForm providerId={provider.id}/></main>}
